import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, '../../');
const webClientRoot = path.resolve(projectRoot, 'web_client');
const projectConfPath = path.resolve(projectRoot, 'automation/project.conf');
const pubspecPath = path.resolve(projectRoot, 'pubspec.yaml');
const packageJsonPath = path.resolve(webClientRoot, 'package.json');
const versionJsPath = path.resolve(webClientRoot, 'src/version.js');

if (!fs.existsSync(projectConfPath)) {
    console.error('Error: automation/project.conf not found');
    process.exit(1);
}

const projectConfContent = fs.readFileSync(projectConfPath, 'utf8');
const versionMatch = projectConfContent.match(/^VERSION=(.+)$/m);

if (!versionMatch) {
    console.error('Error: Could not find VERSION in automation/project.conf');
    process.exit(1);
}

const fullVersion = versionMatch[1].trim();
console.log(`Syncing version from project.conf: ${fullVersion}`);

// 1. Update pubspec.yaml
if (fs.existsSync(pubspecPath)) {
    let content = fs.readFileSync(pubspecPath, 'utf8');
    const regex = /^version:\s*(.+)$/m;
    if (regex.test(content)) {
        const currentParams = content.match(regex)[1];
        if (currentParams.trim() !== fullVersion) {
            content = content.replace(regex, `version: ${fullVersion}`);
            fs.writeFileSync(pubspecPath, content);
            console.log(`Updated pubspec.yaml to ${fullVersion}`);
        } else {
             console.log(`pubspec.yaml already at ${fullVersion}`);
        }
    } else {
        console.warn('Warning: Could not find "version:" in pubspec.yaml');
    }
}

// 2. Update package.json (stripped build number)
const semVer = fullVersion.split('+')[0];
if (fs.existsSync(packageJsonPath)) {
    try {
        const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        if (pkg.version !== semVer) {
            pkg.version = semVer;
            fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n');
            console.log(`Updated package.json to ${semVer}`);
        } else {
             console.log(`package.json already at ${semVer}`);
        }
    } catch (e) {
        console.warn('Error updating package.json', e);
    }
}

// 3. Update src/version.js
const versionJsContent = `// Auto-generated by scripts/sync_version.js
export const APP_VERSION = '${fullVersion}';
`;
fs.writeFileSync(versionJsPath, versionJsContent);
console.log(`Updated src/version.js to ${fullVersion}`);
