import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pubspecPath = path.resolve(__dirname, '../../pubspec.yaml');
const packageJsonPath = path.resolve(__dirname, '../package.json');
const versionJsPath = path.resolve(__dirname, '../src/version.js');

try {
    // 1. Read pubspec.yaml
    const pubspecContent = fs.readFileSync(pubspecPath, 'utf8');
    const versionMatch = pubspecContent.match(/^version:\s*(.+)$/m);

    if (!versionMatch) {
        console.error('Could not find version in pubspec.yaml');
        process.exit(1);
    }

    const fullVersion = versionMatch[1].trim();
    console.log(`Found Flutter version: ${fullVersion}`);

    // Allow splitting version for cleaner package.json (semver compliant)
    // 0.18.2+238 -> 0.18.2
    const semVer = fullVersion.split('+')[0];

    // 2. Update package.json
    if (fs.existsSync(packageJsonPath)) {
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        if (packageJson.version !== semVer) {
            console.log(`Updating package.json version from ${packageJson.version} to ${semVer}`);
            packageJson.version = semVer;
            fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
        }
    }

    // 3. Write src/version.js
    const versionJsContent = `// Auto-generated by scripts/sync_version.js
export const APP_VERSION = '${fullVersion}';
`;
    
    // Check if file content is different to avoid unnecessary writes/reloads
    let currentVersionJs = '';
    if (fs.existsSync(versionJsPath)) {
        currentVersionJs = fs.readFileSync(versionJsPath, 'utf8');
    }

    if (currentVersionJs !== versionJsContent) {
        fs.writeFileSync(versionJsPath, versionJsContent);
        console.log(`Updated ${versionJsPath} with version ${fullVersion}`);
    } else {
        console.log('version.js is up to date.');
    }

} catch (error) {
    console.error('Error syncing version:', error);
    process.exit(1);
}
