CREATE SCHEMA IF NOT EXISTS public;
CREATE SCHEMA IF NOT EXISTS eshop;

-----------------------------------------------
-- 1. Public Independent Tables
-----------------------------------------------

create table if not exists public.organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data JSONB NULL,
  title TEXT NOT NULL,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.occasions_hidden (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  secret TEXT NULL,
  CONSTRAINT occasion_secrets_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.private_keys (
  key TEXT NOT NULL,
  value TEXT NULL,
  CONSTRAINT private_keys_pkey PRIMARY KEY (key)
) TABLESPACE pg_default;

create table if not exists public.role_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title TEXT NOT NULL,
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT role_info_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 2. Eshop Independent Table
-----------------------------------------------

create table if not exists eshop.secrets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  secret TEXT NULL,
  expiry_date TIMESTAMP WITH TIME ZONE NULL,
  CONSTRAINT secrets_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 3. Public Tables depending on organizations, etc.
-----------------------------------------------

create table if not exists public.units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  title TEXT NOT NULL,
  organization BIGINT NOT NULL,
  data JSONB NULL,
  features JSONB NULL,
  CONSTRAINT units_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id),
  CONSTRAINT units_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.user_info (
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  name TEXT NOT NULL,
  surname TEXT NULL,
  sex TEXT NULL,
  phone TEXT NULL,
  id UUID NOT NULL,
  email_readonly TEXT NULL,
  birth_date DATE NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data JSONB NULL,
  organization BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT user_info_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id),
  CONSTRAINT user_info_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id),
  CONSTRAINT user_info_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 4. Eshop Tables depending on eshop.secrets
-----------------------------------------------

create table if not exists eshop.bank_accounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  account_number_human_readable text null,
  secret bigint null,
  account_number text null,
  title text null,
  type text not null default 'FIO'::text,
  min_fetch_wait_seconds bigint null,
  last_fetch_time timestamp with time zone null,
  is_fetch_enabled boolean not null default true,
  constraint bank_accounts_pkey primary key (id),
  constraint bank_accounts_secret_fkey foreign KEY (secret) references eshop.secrets (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 5. Public Tables depending on previous ones
-----------------------------------------------

create table if not exists public.icons (
  link TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data TEXT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  organization BIGINT NOT NULL DEFAULT 1,
  CONSTRAINT icons_pkey PRIMARY KEY (id),
  CONSTRAINT icons_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id)
) TABLESPACE pg_default;

CREATE TABLE if not exists public.request_secrets (
  id serial PRIMARY KEY,
  secret text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ttl_seconds integer NOT NULL
);

create table if not exists public.occasions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  data jsonb null,
  is_hidden boolean not null default false,
  is_open boolean not null default true,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  link text not null,
  title text not null,
  organization bigint not null default '1'::bigint,
  services jsonb null,
  unit bigint not null default '1'::bigint,
  features jsonb null,
  occasion_hidden bigint null,
  description text null,
  is_promoted boolean not null default false,
  is_order_synchronization_enabled boolean not null default true,
  constraint occasions_pkey primary key (id),
  constraint occasions_occasion_hidden_fkey foreign KEY (occasion_hidden) references occasions_hidden (id),
  constraint occasions_unit_fkey foreign KEY (unit) references units (id),
  constraint places_organization_fkey foreign KEY (organization) references organizations (id)
) TABLESPACE pg_default;

create table if not exists public.places (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title TEXT NOT NULL,
  description TEXT NULL,
  type TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL,
  coordinates JSONB NOT NULL DEFAULT '{"latLng": {"lat": 50.0901488, "lng": 14.3979318}}'::jsonb,
  is_hidden BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  occasion BIGINT NULL,
  "order" BIGINT NULL,
  icon BIGINT NULL,
  unit BIGINT NULL,
  CONSTRAINT place_pkey PRIMARY KEY (id),
  CONSTRAINT places_icon_fkey FOREIGN KEY (icon) REFERENCES public.icons (id),
  CONSTRAINT places_unit_fkey FOREIGN KEY (unit) REFERENCES public.units (id),
  CONSTRAINT public_places_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id)
) TABLESPACE pg_default;

create table if not exists public.information_hidden (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data JSONB NULL,
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT information_hidden_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT information_hidden_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 6. Eshop Tables depending on eshop.bank_accounts
-----------------------------------------------

create table if not exists eshop.payment_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  bank_account BIGINT NULL,
  variable_symbol BIGINT NULL,
  amount NUMERIC(10, 2) NULL,
  paid NUMERIC(10, 2) NULL,
  deadline TIMESTAMP WITH TIME ZONE NULL,
  currency_code CHARACTER(3) NOT NULL DEFAULT 'CZK'::bpchar,
  returned NUMERIC(10, 2) NULL,
  paid_externally NUMERIC(10, 2) NULL,
  CONSTRAINT payment_info_bank_account_fkey FOREIGN KEY (bank_account) REFERENCES eshop.bank_accounts (id),
  CONSTRAINT payment_info_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 7. Eshop Tables depending on previous eshop tables and public.occasions
-----------------------------------------------

create table if not exists eshop.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  price NUMERIC(10, 2) NULL,
  state TEXT NULL,
  data JSONB NULL,
  occasion BIGINT NULL,
  payment_info BIGINT NULL,
  currency_code CHARACTER(3) NOT NULL DEFAULT 'CZK'::bpchar,
  note_hidden TEXT NULL,
  CONSTRAINT orders_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT orders_payment_info_fkey FOREIGN KEY (payment_info) REFERENCES eshop.payment_info (id),
  CONSTRAINT orders_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists eshop.orders_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data JSONB NULL,
  "order" BIGINT NOT NULL,
  state TEXT NULL,
  price NUMERIC(10, 2) NULL,
  currency_code CHARACTER(3) NOT NULL DEFAULT 'CZK'::bpchar,
  CONSTRAINT log_orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_history_order_fkey FOREIGN KEY ("order") REFERENCES eshop.orders (id)
) TABLESPACE pg_default;

create table if not exists eshop.bank_account_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_by UUID NOT NULL,
  type TEXT NULL,
  occasion BIGINT NOT NULL,
  bank_account BIGINT NULL,
  note_hidden TEXT NULL,
  state TEXT NULL,
  "order" BIGINT NULL,
  amount NUMERIC(15, 2) NULL,
  CONSTRAINT payment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT bank_account_requests_order_fkey FOREIGN KEY ("order") REFERENCES eshop.orders (id),
  CONSTRAINT payment_requests_bank_account_fkey FOREIGN KEY (bank_account) REFERENCES eshop.bank_accounts (id),
  CONSTRAINT payment_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_info (id),
  CONSTRAINT payment_requests_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id)
) TABLESPACE pg_default;

create table if not exists eshop.transactions (
  id SERIAL NOT NULL,
  transaction_id BIGINT NOT NULL,
  date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  currency CHARACTER(3) NOT NULL,
  counter_account CHARACTER VARYING(34) NULL,
  bank_code CHARACTER(4) NULL,
  bank_name CHARACTER VARYING(255) NULL,
  ks CHARACTER(4) NULL,
  vs CHARACTER(10) NULL,
  ss CHARACTER(10) NULL,
  user_identification TEXT NULL,
  transaction_type CHARACTER VARYING(255) NULL,
  performed_by CHARACTER VARYING(255) NULL,
  comment TEXT NULL,
  command_id BIGINT NULL,
  bank_account_id BIGINT NOT NULL,
  payment_info BIGINT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  message_for_recipient TEXT NULL,
  counter_account_name CHARACTER VARYING(255) NULL,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_bank_account_fkey FOREIGN KEY (bank_account_id) REFERENCES eshop.bank_accounts (id) ON DELETE CASCADE,
  CONSTRAINT transactions_payment_info_fkey FOREIGN KEY (payment_info) REFERENCES eshop.payment_info (id)
) TABLESPACE pg_default;

create table if not exists eshop.unit_bank_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  unit BIGINT NOT NULL,
  bank_account BIGINT NOT NULL,
  CONSTRAINT unit_bank_accounts_bank_account_fkey FOREIGN KEY (bank_account) REFERENCES eshop.bank_accounts (id),
  CONSTRAINT unit_bank_accounts_unit_fkey FOREIGN KEY (unit) REFERENCES public.units (id),
  CONSTRAINT unit_bank_accounts_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists eshop.bank_account_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  bank_account BIGINT NOT NULL,
  "user" UUID NOT NULL,
  is_support BOOLEAN NOT NULL DEFAULT false,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT bank_account_user_bank_account_fkey FOREIGN KEY (bank_account) REFERENCES eshop.bank_accounts (id),
  CONSTRAINT bank_account_user_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id),
  CONSTRAINT bank_account_user_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists eshop.planned_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  change_type TEXT NOT NULL,
  subject_id BIGINT NOT NULL,
  new_value TEXT NOT NULL,
  change_time TIMESTAMP WITH TIME ZONE NOT NULL,
  applied BOOLEAN NOT NULL DEFAULT false,
  occasion BIGINT NULL,
  CONSTRAINT planned_changes_pkey PRIMARY KEY (id),
  CONSTRAINT planned_changes_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id)
) TABLESPACE pg_default;

create table if not exists eshop.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  ticket_symbol TEXT NULL,
  state TEXT NULL,
  occasion BIGINT NOT NULL,
  note TEXT NULL,
  note_hidden TEXT NULL,
  CONSTRAINT tickets_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT ticket_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 8. Eshop Tables depending on public.occasions and eshop.product_types
-----------------------------------------------

create table if not exists eshop.product_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  title TEXT NULL,
  description TEXT NULL,
  type TEXT NULL,
  data JSONB NULL,
  occasion BIGINT NULL,
  maximum BIGINT NULL,
  CONSTRAINT item_types_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT products_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists eshop.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  title TEXT NULL,
  description TEXT NULL,
  price NUMERIC(10, 2) NULL,
  data JSONB NULL,
  product_type BIGINT NULL,
  occasion BIGINT NULL,
  is_hidden BOOLEAN NOT NULL DEFAULT false,
  currency_code CHARACTER(3) NOT NULL DEFAULT 'CZK'::bpchar,
  title_short TEXT NULL,
  "order" BIGINT NULL,
  maximum BIGINT NULL,
  CONSTRAINT options_pkey PRIMARY KEY (id),
  CONSTRAINT items_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT products_product_type_fkey FOREIGN KEY (product_type) REFERENCES eshop.product_types (id)
) TABLESPACE pg_default;

create table if not exists eshop.order_product_ticket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "order" BIGINT NULL,
  product BIGINT NULL,
  ticket BIGINT NULL,
  CONSTRAINT order_item_pkey PRIMARY KEY (id),
  CONSTRAINT order_item_order_fkey FOREIGN KEY ("order") REFERENCES eshop.orders (id),
  CONSTRAINT order_item_ticket_ticket_fkey FOREIGN KEY (ticket) REFERENCES eshop.tickets (id),
  CONSTRAINT order_product_ticket_product_fkey FOREIGN KEY (product) REFERENCES eshop.products (id)
) TABLESPACE pg_default;

create table if not exists eshop.blueprints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data JSONB NULL,
  title TEXT NULL,
  organization BIGINT NOT NULL DEFAULT '1'::bigint,
  configuration JSONB NULL,
  objects JSONB NULL,
  groups JSONB NULL,
  occasion BIGINT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  background_svg TEXT NULL,
  CONSTRAINT blueprints_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT blueprints_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id),
  CONSTRAINT blueprints_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists eshop.spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  occasion BIGINT NOT NULL,
  product BIGINT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  secret UUID NULL,
  secret_expiration_time TIMESTAMP WITH TIME ZONE NULL,
  title TEXT NULL,
  order_product_ticket BIGINT NULL,
  blueprint BIGINT NULL,
  CONSTRAINT spots_pkey PRIMARY KEY (id),
  CONSTRAINT spots_blueprint_fkey FOREIGN KEY (blueprint) REFERENCES eshop.blueprints (id),
  CONSTRAINT spots_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT spots_order_product_ticket_fkey FOREIGN KEY (order_product_ticket) REFERENCES eshop.order_product_ticket (id),
  CONSTRAINT spots_product_fkey FOREIGN KEY (product) REFERENCES eshop.products (id)
) TABLESPACE pg_default;

-----------------------------------------------
-- 9. Public Tables that reference both public and eshop tables
-----------------------------------------------

create table if not exists public.email_templates (
  id bigint generated by default as identity not null,
  html text null,
  occasion bigint null,
  subject text null,
  organization bigint null,
  code text null,
  unit bigint null,
  title text null,
  constraint email_templates_pkey primary key (id),
  constraint email_templates_organization_fkey foreign KEY (organization) references organizations (id),
  constraint email_templates_unit_fkey foreign KEY (unit) references units (id),
  constraint public_email_templates_occasion_fkey foreign KEY (occasion) references occasions (id)
)  TABLESPACE pg_default;

create table if not exists public.email_wrappers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  organization bigint null,
  unit bigint null,
  html text null,
  occasion bigint null,
  constraint email_wrappers_pkey primary key (id),
  constraint email_wrappers_occasion_fkey foreign KEY (occasion) references occasions (id),
  constraint email_wrappers_organization_fkey foreign KEY (organization) references organizations (id),
  constraint email_wrappers_unit_fkey foreign KEY (unit) references units (id)
) TABLESPACE pg_default;

create table if not exists public.user_group_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title TEXT NOT NULL,
  leader UUID NULL,
  place BIGINT NULL,
  description TEXT NULL,
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  data JSONB NULL,
  type TEXT NULL,
  CONSTRAINT public_user_group_info_leader_fkey FOREIGN KEY (leader) REFERENCES public.user_info (id),
  CONSTRAINT public_user_group_info_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT user_group_info_place_fkey FOREIGN KEY (place) REFERENCES public.places (id),
  CONSTRAINT user_group_info_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.log_app_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  organization BIGINT NOT NULL,
  platform JSONB NOT NULL,
  CONSTRAINT log_app_config_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.log_notifications (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  user_id UUID NOT NULL DEFAULT auth.uid(),
  content TEXT NOT NULL,
  heading TEXT NULL,
  "to" JSONB NULL,
  organization BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT log_notifications_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id),
  CONSTRAINT public_log_notifications_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT log_notifications_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  link TEXT NOT NULL,
  occasion BIGINT NULL,
  unit BIGINT NULL,
  CONSTRAINT images_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT images_unit_fkey FOREIGN KEY (unit) REFERENCES public.units (id),
  CONSTRAINT images_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.log_emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "to" TEXT NOT NULL,
  template TEXT NULL,
  "from" TEXT NULL,
  organization BIGINT NOT NULL DEFAULT '1'::bigint,
  occasion BIGINT NULL,
  unit BIGINT NULL,
  CONSTRAINT log_emails_pkey PRIMARY KEY (id),
  CONSTRAINT log_emails_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT log_emails_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id),
  CONSTRAINT log_emails_unit_fkey FOREIGN KEY (unit) REFERENCES public.units (id)
) TABLESPACE pg_default;

create table if not exists public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  title TEXT NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  max_participants BIGINT NULL,
  description TEXT NULL,
  place BIGINT NULL,
  split_for_men_women BOOLEAN NOT NULL DEFAULT false,
  is_group_event BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  is_hidden BOOLEAN NOT NULL DEFAULT false,
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  type TEXT NULL,
  CONSTRAINT events_place_fkey FOREIGN KEY (place) REFERENCES public.places (id),
  CONSTRAINT public_events_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT events_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.event_groups (
  event_parent BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_child BIGINT NOT NULL,
  CONSTRAINT event_groups_event_child_fkey FOREIGN KEY (event_child) REFERENCES public.events (id),
  CONSTRAINT event_groups_event_parent_fkey FOREIGN KEY (event_parent) REFERENCES public.events (id),
  CONSTRAINT event_group_pkey PRIMARY KEY (event_parent, event_child)
) TABLESPACE pg_default;

create table if not exists public.event_users_saved (
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  event BIGINT NOT NULL,
  "user" UUID NOT NULL,
  CONSTRAINT event_users_saved_pkey PRIMARY KEY ("user", event),
  CONSTRAINT event_users_saved_event_fkey FOREIGN KEY (event) REFERENCES public.events (id),
  CONSTRAINT event_users_saved_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id)
) TABLESPACE pg_default;

create table if not exists public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  message TEXT NULL,
  created_by UUID NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT news_pkey PRIMARY KEY (id),
  CONSTRAINT news_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_info (id),
  CONSTRAINT public_news_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id)
) TABLESPACE pg_default;

create table if not exists public.exclusive_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title TEXT NOT NULL,
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT public_exclusive_groups_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT exclusive_group_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.exclusive_events (
  event BIGINT NOT NULL,
  "group" BIGINT NOT NULL,
  CONSTRAINT exclusive_events_pkey PRIMARY KEY (event, "group"),
  CONSTRAINT exclusive_events_event_fkey FOREIGN KEY (event) REFERENCES public.events (id),
  CONSTRAINT exclusive_events_group_fkey FOREIGN KEY ("group") REFERENCES public.exclusive_groups (id)
) TABLESPACE pg_default;

create table if not exists public.information (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  title TEXT NULL,
  description TEXT NULL,
  is_hidden BOOLEAN NOT NULL DEFAULT false,
  "order" BIGINT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  type TEXT NULL,
  occasion BIGINT NULL,
  data JSONB NULL,
  information_hidden BIGINT NULL,
  unit BIGINT NULL,
  CONSTRAINT information_pkey PRIMARY KEY (id),
  CONSTRAINT information_information_hidden_fkey FOREIGN KEY (information_hidden) REFERENCES public.information_hidden (id),
  CONSTRAINT information_unit_fkey FOREIGN KEY (unit) REFERENCES public.units (id),
  CONSTRAINT public_information_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id)
) TABLESPACE pg_default;

create table if not exists public.occasion_users (
  occasion BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "user" UUID NOT NULL,
  is_editor BOOLEAN NOT NULL DEFAULT false,
  is_manager BOOLEAN NOT NULL DEFAULT false,
  is_approved BOOLEAN NOT NULL DEFAULT false,
  is_approver BOOLEAN NOT NULL DEFAULT false,
  data JSONB NULL,
  role BIGINT NULL,
  services JSONB NULL,
  is_editor_view BOOLEAN NOT NULL DEFAULT false,
  is_editor_order boolean NOT NULL DEFAULT false,
  is_editor_order_view boolean NOT NULL DEFAULT false,
  CONSTRAINT public_occasion_users_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT public_occasion_users_role_fkey FOREIGN KEY (role) REFERENCES public.role_info (id),
  CONSTRAINT occasion_users_pkey PRIMARY KEY (occasion, "user")
) TABLESPACE pg_default;

create table if not exists public.organization_users (
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "user" UUID NOT NULL,
  organization BIGINT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT organization_users_pkey PRIMARY KEY (organization, "user"),
  CONSTRAINT organization_users_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations (id),
  CONSTRAINT organization_users_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id)
) TABLESPACE pg_default;

create table if not exists public.user_companions (
  "user" UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  companion UUID NOT NULL,
  CONSTRAINT user_companions_pkey PRIMARY KEY ("user", companion),
  CONSTRAINT user_companions_companion_fkey FOREIGN KEY (companion) REFERENCES public.user_info (id),
  CONSTRAINT user_companions_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id)
) TABLESPACE pg_default;

create table if not exists public.user_groups (
  "user" UUID NOT NULL,
  "group" BIGINT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT user_groups_pkey PRIMARY KEY ("user", "group"),
  CONSTRAINT user_groups_group_fkey FOREIGN KEY ("group") REFERENCES public.user_group_info (id),
  CONSTRAINT user_groups_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id)
) TABLESPACE pg_default;

create table if not exists public.user_reset_token (
  token UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "user" UUID NOT NULL,
  CONSTRAINT public_user_token_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id),
  CONSTRAINT user_token_pkey PRIMARY KEY ("user")
) TABLESPACE pg_default;

-----------------------------------------------
-- 10. Public Tables with cross-schema dependencies
-----------------------------------------------

create table if not exists public.forms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data JSONB NULL,
  key UUID NOT NULL DEFAULT gen_random_uuid(),
  occasion BIGINT NULL,
  type TEXT NULL,
  bank_account BIGINT NULL,
  deadline_duration_seconds BIGINT NULL,
  is_open BOOLEAN NOT NULL DEFAULT true,
  link TEXT NULL,
  blueprint BIGINT NULL,
  header TEXT NULL,
  header_off TEXT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT forms_bank_account_fkey FOREIGN KEY (bank_account) REFERENCES eshop.bank_accounts (id),
  CONSTRAINT forms_blueprint_fkey FOREIGN KEY (blueprint) REFERENCES eshop.blueprints (id),
  CONSTRAINT forms_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id),
  CONSTRAINT forms_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table if not exists public.unit_users (
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  unit BIGINT NOT NULL,
  "user" UUID NOT NULL,
  is_manager BOOLEAN NOT NULL DEFAULT false,
  is_editor BOOLEAN NOT NULL DEFAULT false,
  data JSONB NULL,
  is_editor_view BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT unit_users_pkey PRIMARY KEY (unit, "user"),
  CONSTRAINT unit_users_unit_fkey FOREIGN KEY (unit) REFERENCES public.units (id),
  CONSTRAINT unit_users_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id)
) TABLESPACE pg_default;

create table if not exists public.event_roles (
  event BIGINT NOT NULL,
  role BIGINT NOT NULL,
  CONSTRAINT event_roles_pkey PRIMARY KEY (event, role),
  CONSTRAINT public_event_roles_event_fkey FOREIGN KEY (event) REFERENCES public.events (id),
  CONSTRAINT public_event_roles_role_fkey FOREIGN KEY (role) REFERENCES public.role_info (id)
) TABLESPACE pg_default;

create table if not exists public.event_users (
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  event BIGINT NOT NULL,
  "user" UUID NOT NULL,
  CONSTRAINT event_users_event_fkey FOREIGN KEY (event) REFERENCES public.events (id),
  CONSTRAINT event_users_user_fkey FOREIGN KEY ("user") REFERENCES public.user_info (id),
  CONSTRAINT event_users_pkey PRIMARY KEY (event, "user")
) TABLESPACE pg_default;

create table if not exists public.form_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  title TEXT NULL,
  description TEXT NULL,
  data JSONB NULL,
  type TEXT NULL,
  is_required BOOLEAN NOT NULL DEFAULT false,
  form BIGINT NOT NULL,
  is_hidden BOOLEAN NOT NULL DEFAULT false,
  "order" BIGINT NULL,
  product_type BIGINT NULL,
  is_ticket_field BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT form_fields_pkey PRIMARY KEY (id),
  CONSTRAINT form_fields_form_fkey FOREIGN KEY (form) REFERENCES public.forms (id),
  CONSTRAINT form_fields_product_type_fkey FOREIGN KEY (product_type) REFERENCES eshop.product_types (id)
) TABLESPACE pg_default;

create table if not exists public.user_news (
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  news_id BIGINT NOT NULL,
  "user" UUID NOT NULL,
  occasion BIGINT NOT NULL DEFAULT '1'::bigint,
  CONSTRAINT user_news_pkey PRIMARY KEY ("user", occasion),
  CONSTRAINT user_news_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news (id),
  CONSTRAINT user_news_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id)
) TABLESPACE pg_default;
