-- Canonical schema source for event feedback.
-- Recovered definition verified against the Festapp A production catalog on
-- 2026-08-02. Deployment remains migration-driven; this file is source only.

CREATE TABLE IF NOT EXISTS public.event_feedback (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  event       bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  occasion    bigint NOT NULL REFERENCES public.occasions(id) ON DELETE CASCADE,
  "user"      uuid REFERENCES public.user_info(id) ON DELETE SET NULL,
  client_id   uuid,
  rating      text NOT NULL,
  note        text,
  data        jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT event_feedback_identity_check
    CHECK (("user" IS NOT NULL) OR (client_id IS NOT NULL)),
  CONSTRAINT event_feedback_rating_check
    CHECK (rating = ANY (ARRAY['happy'::text, 'neutral'::text, 'sad'::text])),
  CONSTRAINT event_feedback_note_length_check
    CHECK (char_length(COALESCE(note, ''::text)) <= 2000)
);

CREATE UNIQUE INDEX IF NOT EXISTS event_feedback_event_user_uidx
  ON public.event_feedback USING btree (event, "user")
  WHERE ("user" IS NOT NULL);

CREATE UNIQUE INDEX IF NOT EXISTS event_feedback_event_client_uidx
  ON public.event_feedback USING btree (event, client_id)
  WHERE (("user" IS NULL) AND (client_id IS NOT NULL));

CREATE INDEX IF NOT EXISTS event_feedback_event_idx
  ON public.event_feedback USING btree (event);

ALTER TABLE public.event_feedback ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.event_feedback FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.event_feedback TO service_role;

REVOKE ALL ON SEQUENCE public.event_feedback_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.event_feedback_id_seq
  TO service_role;
