
const fs = require('fs');
const path = require('path');

// 1. Get Version from Args or Env
const version = process.argv[2] || process.env.VERSION;

if (!version) {
    console.error('Error: No version provided. Usage: node configure_version.js <version>');
    process.exit(1);
}

console.log(`Configuring Version: ${version}`);

const projectRoot = path.resolve(__dirname, '../');
const webClientRoot = path.resolve(projectRoot, 'web_client');

// Paths
const pubspecPath = path.resolve(projectRoot, 'pubspec.yaml');
const packageJsonPath = path.resolve(webClientRoot, 'package.json');
const versionJsPath = path.resolve(webClientRoot, 'src/version.js');

// 2. Update pubspec.yaml
if (fs.existsSync(pubspecPath)) {
    let content = fs.readFileSync(pubspecPath, 'utf8');
    // Regex to replace version: x.x.x+x
    const regex = /^version:\s*(.+)$/m;
    if (regex.test(content)) {
        const currentParams = content.match(regex)[1];
        if (currentParams.trim() !== version) {
            content = content.replace(regex, `version: ${version}`);
            fs.writeFileSync(pubspecPath, content);
            console.log(`Updated pubspec.yaml to ${version}`);
        } else {
             console.log(`pubspec.yaml already at ${version}`);
        }
    } else {
        console.warn('Warning: Could not find "version:" in pubspec.yaml');
    }
} else {
    console.warn(`Warning: pubspec.yaml not found at ${pubspecPath}`);
}

// 3. Update package.json
// Package.json versions should be semver (no +build).
const semVer = version.split('+')[0];

if (fs.existsSync(packageJsonPath)) {
    try {
        const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        if (pkg.version !== semVer) {
            pkg.version = semVer;
            fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n');
            console.log(`Updated package.json to ${semVer}`);
        } else {
            console.log(`package.json already at ${semVer}`);
        }
    } catch (e) {
        console.error('Error parsing package.json:', e);
    }
} else {
    console.warn(`Warning: package.json not found at ${packageJsonPath}`);
}

// 4. Update src/version.js
const versionJsContent = `// Auto-generated by automation/configure_version.js
export const APP_VERSION = '${version}';
`;

let currentVersionJs = '';
if (fs.existsSync(versionJsPath)) {
    currentVersionJs = fs.readFileSync(versionJsPath, 'utf8');
}

if (currentVersionJs !== versionJsContent) {
    fs.writeFileSync(versionJsPath, versionJsContent);
    console.log(`Updated src/version.js to ${version}`);
} else {
    console.log(`src/version.js is up to date.`);
}
