-- Foundation for canonical EUR references and transaction pairing.
-- Customer-visible RF issuance is intentionally deferred to the activation migration.

ALTER TABLE eshop.payment_info ADD COLUMN IF NOT EXISTS creditor_reference text;
ALTER TABLE eshop.transactions ADD COLUMN IF NOT EXISTS payer_reference text;
ALTER TABLE eshop.transactions ADD COLUMN IF NOT EXISTS ingest_source text;
ALTER TABLE eshop.bank_accounts ADD COLUMN IF NOT EXISTS creditor_name text;

UPDATE eshop.transactions SET ingest_source = CASE
  WHEN transaction_type = 'manual' THEN 'manual'
  WHEN external_id IS NOT NULL THEN 'legacy_email'
  WHEN transaction_id IS NOT NULL THEN 'legacy_api'
  ELSE 'legacy' END
WHERE ingest_source IS NULL;
ALTER TABLE eshop.transactions ALTER COLUMN ingest_source SET DEFAULT 'legacy';
ALTER TABLE eshop.transactions ALTER COLUMN ingest_source SET NOT NULL;
ALTER TABLE eshop.bank_accounts DROP CONSTRAINT IF EXISTS bank_accounts_creditor_name_check;
ALTER TABLE eshop.bank_accounts ADD CONSTRAINT bank_accounts_creditor_name_check
  CHECK (creditor_name IS NULL OR length(trim(creditor_name)) BETWEEN 1 AND 70);

CREATE TABLE IF NOT EXISTS eshop.transaction_pairing_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  transaction_snapshot_id bigint NOT NULL,
  transaction_id integer NULL REFERENCES eshop.transactions(id) ON DELETE SET NULL,
  old_payment_info_id bigint NULL REFERENCES eshop.payment_info(id) ON DELETE SET NULL,
  new_payment_info_id bigint NULL REFERENCES eshop.payment_info(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN ('paired', 'unpaired', 'manual_deleted')),
  method text NOT NULL,
  actor_id uuid NULL,
  actor_kind text NOT NULL CHECK (actor_kind IN ('service', 'user', 'system')),
  details jsonb NOT NULL DEFAULT '{}'::jsonb
);
ALTER TABLE eshop.transaction_pairing_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE eshop.transaction_pairing_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE eshop.transaction_pairing_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE eshop.transaction_pairing_events_id_seq TO service_role;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM eshop.transactions WHERE transaction_id IS NOT NULL
    GROUP BY bank_account_id, transaction_id HAVING count(*) > 1) THEN
    RAISE EXCEPTION 'DUPLICATE_BANK_MOVEMENT_ID_PREVENTS_CUTOVER'; END IF;
  IF EXISTS (SELECT 1 FROM eshop.transactions WHERE external_id IS NOT NULL
    GROUP BY bank_account_id, external_id HAVING count(*) > 1) THEN
    RAISE EXCEPTION 'DUPLICATE_EMAIL_TRANSPORT_ID_PREVENTS_CUTOVER'; END IF;
END; $$;
CREATE UNIQUE INDEX IF NOT EXISTS transactions_bank_movement_uidx
  ON eshop.transactions(bank_account_id, transaction_id) WHERE transaction_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS transactions_email_transport_uidx
  ON eshop.transactions(bank_account_id, external_id) WHERE external_id IS NOT NULL;


-- Source: database/functions/eshop_transactions/payment_reference.sql
CREATE OR REPLACE FUNCTION public.normalize_creditor_reference(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = public, extensions
AS $$
  SELECT upper(regexp_replace(p_value, '[[:space:]]', '', 'g'));
$$;

CREATE OR REPLACE FUNCTION public.is_valid_creditor_reference(p_value text)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
STRICT
SET search_path = public, extensions
AS $$
DECLARE
  v_value text := public.normalize_creditor_reference(p_value);
  v_rearranged text;
  v_expanded text := '';
  v_char text;
  v_remainder integer := 0;
  v_index integer;
BEGIN
  IF v_value !~ '^RF[0-9]{2}[A-Z0-9]{1,21}$' THEN
    RETURN false;
  END IF;

  v_rearranged := substring(v_value FROM 5) || substring(v_value FROM 1 FOR 4);
  FOR v_index IN 1..length(v_rearranged) LOOP
    v_char := substring(v_rearranged FROM v_index FOR 1);
    IF v_char ~ '[0-9]' THEN
      v_expanded := v_expanded || v_char;
    ELSE
      v_expanded := v_expanded || (ascii(v_char) - 55)::text;
    END IF;
  END LOOP;

  FOR v_index IN 1..length(v_expanded) LOOP
    v_remainder := (v_remainder * 10 + substring(v_expanded FROM v_index FOR 1)::integer) % 97;
  END LOOP;
  RETURN v_remainder = 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.generate_creditor_reference(p_variable_symbol bigint)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
STRICT
SET search_path = public, extensions
AS $$
DECLARE
  v_payload text;
  v_expanded text := '';
  v_char text;
  v_remainder integer := 0;
  v_index integer;
  v_result text;
BEGIN
  IF p_variable_symbol <= 0 OR p_variable_symbol > 9999999999 THEN
    RAISE EXCEPTION 'PAYMENT_REFERENCE_INVALID_VARIABLE_SYMBOL';
  END IF;
  v_payload := p_variable_symbol::text;

  FOR v_index IN 1..length(v_payload || 'RF00') LOOP
    v_char := substring(v_payload || 'RF00' FROM v_index FOR 1);
    IF v_char ~ '[0-9]' THEN
      v_expanded := v_expanded || v_char;
    ELSE
      v_expanded := v_expanded || (ascii(v_char) - 55)::text;
    END IF;
  END LOOP;
  FOR v_index IN 1..length(v_expanded) LOOP
    v_remainder := (v_remainder * 10 + substring(v_expanded FROM v_index FOR 1)::integer) % 97;
  END LOOP;
  v_result := 'RF' || lpad((98 - v_remainder)::text, 2, '0') || v_payload;
  IF NOT public.is_valid_creditor_reference(v_result) THEN
    RAISE EXCEPTION 'PAYMENT_REFERENCE_GENERATION_FAILED';
  END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_valid_iban(p_value text)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
STRICT
SET search_path = public, extensions
AS $$
DECLARE
  v_iban text := upper(regexp_replace(p_value, '[[:space:]]', '', 'g'));
  v_rearranged text;
  v_char text;
  v_expanded text;
  v_remainder integer := 0;
  v_index integer;
  v_digit_index integer;
BEGIN
  IF v_iban !~ '^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$' THEN RETURN false; END IF;
  v_rearranged := substring(v_iban FROM 5) || substring(v_iban FROM 1 FOR 4);
  FOR v_index IN 1..length(v_rearranged) LOOP
    v_char := substring(v_rearranged FROM v_index FOR 1);
    v_expanded := CASE WHEN v_char ~ '[0-9]' THEN v_char ELSE (ascii(v_char) - 55)::text END;
    FOR v_digit_index IN 1..length(v_expanded) LOOP
      v_remainder := (v_remainder * 10 + substring(v_expanded FROM v_digit_index FOR 1)::integer) % 97;
    END LOOP;
  END LOOP;
  RETURN v_remainder = 1;
END;
$$;


-- Source: database/functions/eshop_transactions/apply_transaction_pairing.sql
CREATE OR REPLACE FUNCTION public.apply_transaction_pairing(
  p_transaction_id bigint,
  p_payment_info_id bigint,
  p_method text,
  p_actor_kind text DEFAULT 'system',
  p_details jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_transaction eshop.transactions%ROWTYPE;
  v_target eshop.payment_info%ROWTYPE;
  v_old_payment_info_id bigint;
  v_order_id bigint;
BEGIN
  IF p_method IS NULL OR p_method !~ '^[a-z0-9_]{1,64}$' THEN
    RAISE EXCEPTION 'PAIRING_INVALID_METHOD';
  END IF;
  IF p_actor_kind NOT IN ('service', 'user', 'system') THEN
    RAISE EXCEPTION 'PAIRING_INVALID_ACTOR_KIND';
  END IF;

  SELECT * INTO v_transaction
  FROM eshop.transactions
  WHERE id = p_transaction_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PAIRING_TRANSACTION_NOT_FOUND'; END IF;
  v_old_payment_info_id := v_transaction.payment_info;

  IF v_old_payment_info_id IS NOT DISTINCT FROM p_payment_info_id THEN
    RETURN jsonb_build_object('status', 'unchanged', 'transaction_id', p_transaction_id,
      'payment_info_id', p_payment_info_id);
  END IF;

  IF p_payment_info_id IS NOT NULL THEN
    SELECT * INTO v_target FROM eshop.payment_info WHERE id = p_payment_info_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'PAIRING_PAYMENT_INFO_NOT_FOUND'; END IF;
    IF upper(trim(v_transaction.currency::text)) <> upper(trim(v_target.currency_code::text)) THEN
      RAISE EXCEPTION 'PAIRING_CURRENCY_MISMATCH';
    END IF;
    IF v_transaction.transaction_type IS DISTINCT FROM 'manual'
       AND v_transaction.bank_account_id <> v_target.bank_account THEN
      RAISE EXCEPTION 'PAIRING_BANK_ACCOUNT_MISMATCH';
    END IF;
  END IF;

  UPDATE eshop.transactions SET payment_info = p_payment_info_id WHERE id = p_transaction_id;

  IF v_old_payment_info_id IS NOT NULL THEN
    UPDATE eshop.payment_info pi SET
      paid = COALESCE((SELECT sum(t.amount) FROM eshop.transactions t
        WHERE t.payment_info = pi.id AND t.transaction_type IS DISTINCT FROM 'return'), 0),
      returned = COALESCE((SELECT abs(sum(t.amount)) FROM eshop.transactions t
        WHERE t.payment_info = pi.id AND t.transaction_type = 'return'), 0)
    WHERE pi.id = v_old_payment_info_id;
    SELECT o.id INTO v_order_id FROM eshop.orders o WHERE o.payment_info = v_old_payment_info_id;
    IF v_order_id IS NOT NULL THEN PERFORM public.recalculate_order_payment_status(v_order_id); END IF;
  END IF;

  IF p_payment_info_id IS NOT NULL THEN
    UPDATE eshop.payment_info pi SET
      paid = COALESCE((SELECT sum(t.amount) FROM eshop.transactions t
        WHERE t.payment_info = pi.id AND t.transaction_type IS DISTINCT FROM 'return'), 0),
      returned = COALESCE((SELECT abs(sum(t.amount)) FROM eshop.transactions t
        WHERE t.payment_info = pi.id AND t.transaction_type = 'return'), 0)
    WHERE pi.id = p_payment_info_id;
    SELECT o.id INTO v_order_id FROM eshop.orders o WHERE o.payment_info = p_payment_info_id;
    IF v_order_id IS NOT NULL THEN PERFORM public.recalculate_order_payment_status(v_order_id); END IF;
  END IF;

  INSERT INTO eshop.transaction_pairing_events (
    transaction_snapshot_id, transaction_id, old_payment_info_id,
    new_payment_info_id, action, method, actor_id, actor_kind, details
  ) VALUES (
    p_transaction_id, p_transaction_id, v_old_payment_info_id,
    p_payment_info_id, CASE WHEN p_payment_info_id IS NULL THEN 'unpaired' ELSE 'paired' END,
    p_method, auth.uid(), p_actor_kind, COALESCE(p_details, '{}'::jsonb)
  );

  RETURN jsonb_build_object('status', CASE WHEN p_payment_info_id IS NULL THEN 'unpaired' ELSE 'paired' END,
    'transaction_id', p_transaction_id, 'payment_info_id', p_payment_info_id);
END;
$$;

REVOKE ALL ON FUNCTION public.apply_transaction_pairing(bigint,bigint,text,text,jsonb)
  FROM PUBLIC, anon, authenticated, service_role;


-- Source: database/functions/eshop_transactions/match_bank_transaction.sql
CREATE OR REPLACE FUNCTION public.match_bank_transaction(p_transaction_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_transaction eshop.transactions%ROWTYPE;
  v_candidate_ids bigint[];
  v_candidate_id bigint;
  v_signal_count integer := 0;
BEGIN
  PERFORM public.require_service_role();

  SELECT * INTO v_transaction
  FROM eshop.transactions
  WHERE id = p_transaction_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'MATCH_TRANSACTION_NOT_FOUND'; END IF;

  IF v_transaction.payment_info IS NOT NULL THEN
    RETURN jsonb_build_object('verdict', 'already_paired',
      'transaction_id', p_transaction_id, 'payment_info_id', v_transaction.payment_info);
  END IF;
  IF v_transaction.amount <= 0
     OR v_transaction.bank_account_id IS NULL
     OR nullif(trim(v_transaction.currency::text), '') IS NULL THEN
    RETURN jsonb_build_object('verdict', 'ineligible', 'reason', 'invalid_direction_or_scope');
  END IF;
  IF v_transaction.ingest_source LIKE '%_email'
     AND v_transaction.transaction_id IS NULL
     AND v_transaction.command_id IS NULL THEN
    RETURN jsonb_build_object('verdict', 'ineligible', 'reason', 'unverified_identity');
  END IF;

  WITH raw_signals(kind, value) AS (
    SELECT 'vs', trim(v_transaction.vs::text)
      WHERE trim(COALESCE(v_transaction.vs::text, '')) ~ '^[0-9]{1,10}$'
    UNION ALL
    SELECT 'rf', public.normalize_creditor_reference(v_transaction.payer_reference)
      WHERE v_transaction.payer_reference IS NOT NULL
        AND public.is_valid_creditor_reference(v_transaction.payer_reference)
    UNION ALL
    SELECT 'rf', public.normalize_creditor_reference(m.captures[2])
      FROM regexp_matches(
        upper(concat_ws(E'\n', v_transaction.message_for_recipient,
          v_transaction.user_identification, v_transaction.comment)),
        '(^|[^A-Z0-9])(RF[0-9]{2}[A-Z0-9[:space:]]{1,25})([^A-Z0-9]|$)', 'g'
      ) AS m(captures)
      WHERE public.is_valid_creditor_reference(m.captures[2])
    UNION ALL
    SELECT 'vs', trim(v_transaction.message_for_recipient)
      WHERE nullif(trim(COALESCE(v_transaction.vs::text, '')), '') IS NULL
        AND trim(COALESCE(v_transaction.message_for_recipient, '')) ~ '^[0-9]{1,10}$'
    UNION ALL
    SELECT 'vs', substring(v_transaction.message_for_recipient
      FROM '(?i)(?:VS|variabilní symbol)[[:space:]]*[:=-]?[[:space:]]*([0-9]{1,10})')
      WHERE nullif(trim(COALESCE(v_transaction.vs::text, '')), '') IS NULL
        AND substring(v_transaction.message_for_recipient
          FROM '(?i)(?:VS|variabilní symbol)[[:space:]]*[:=-]?[[:space:]]*([0-9]{1,10})') IS NOT NULL
  ), signals AS (
    SELECT DISTINCT kind, value FROM raw_signals
  ), candidates AS (
    SELECT DISTINCT pi.id
    FROM signals s
    JOIN eshop.payment_info pi
      ON (s.kind = 'rf' AND pi.creditor_reference = s.value)
      OR (s.kind = 'vs' AND pi.variable_symbol = s.value::bigint)
    WHERE pi.bank_account = v_transaction.bank_account_id
      AND upper(trim(pi.currency_code::text)) = upper(trim(v_transaction.currency::text))
  )
  SELECT (SELECT count(*) FROM signals), array_agg(c.id ORDER BY c.id)
  INTO v_signal_count, v_candidate_ids
  FROM candidates c;

  IF v_signal_count = 0 OR v_candidate_ids IS NULL THEN
    RETURN jsonb_build_object('verdict', 'unmatched', 'reason', 'no_unique_reference');
  END IF;
  IF cardinality(v_candidate_ids) <> 1 THEN
    RETURN jsonb_build_object('verdict', 'ambiguous', 'candidate_count', cardinality(v_candidate_ids));
  END IF;

  v_candidate_id := v_candidate_ids[1];
  PERFORM public.apply_transaction_pairing(
    p_transaction_id, v_candidate_id, 'automatic_reference', 'service',
    jsonb_build_object('signal_count', v_signal_count)
  );
  RETURN jsonb_build_object('verdict', 'paired', 'transaction_id', p_transaction_id,
    'payment_info_id', v_candidate_id);
END;
$$;

REVOKE ALL ON FUNCTION public.match_bank_transaction(bigint)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.match_bank_transaction(bigint) TO service_role;


-- Source: database/functions/eshop_transactions/insert_transactions.sql
CREATE OR REPLACE FUNCTION public.insert_transactions(transactions jsonb, bank_account_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_input jsonb;
  v_date timestamptz;
  v_id bigint;
  v_movement_id bigint;
  v_result jsonb;
  v_items jsonb := '[]'::jsonb;
  v_inserted integer := 0;
  v_skipped integer := 0;
BEGIN
  PERFORM public.require_service_role();
  IF jsonb_typeof(transactions) <> 'array' THEN RAISE EXCEPTION 'TRANSACTIONS_ARRAY_REQUIRED'; END IF;

  FOR v_input IN SELECT value FROM jsonb_array_elements(transactions) LOOP
    BEGIN
      v_date := (v_input->'column0'->>'value')::timestamptz;
      v_movement_id := nullif(v_input->'column22'->>'value', '')::bigint;
    EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow THEN
      v_skipped := v_skipped + 1;
      v_items := v_items || jsonb_build_array(jsonb_build_object(
        'ingest_status', 'failed', 'reason', 'invalid_bank_payload'));
      CONTINUE;
    END;

    SELECT t.id INTO v_id FROM eshop.transactions t
    WHERE t.bank_account_id = insert_transactions.bank_account_id
      AND t.transaction_id = v_movement_id;
    IF v_id IS NOT NULL THEN
      v_skipped := v_skipped + 1;
      v_items := v_items || jsonb_build_array(jsonb_build_object(
        'source_id', v_movement_id, 'stored_id', v_id,
        'ingest_status', 'skipped', 'match_verdict', 'already_ingested'));
      CONTINUE;
    END IF;

    INSERT INTO eshop.transactions (
      transaction_id, date, amount, currency, counter_account, bank_code,
      bank_name, ks, vs, ss, user_identification, transaction_type,
      performed_by, comment, command_id, bank_account_id,
      message_for_recipient, counter_account_name, payer_reference, ingest_source
    ) VALUES (
      v_movement_id, v_date, (v_input->'column1'->>'value')::numeric,
      v_input->'column14'->>'value', v_input->'column2'->>'value',
      v_input->'column3'->>'value', v_input->'column12'->>'value',
      nullif(v_input->'column4'->>'value', ''), nullif(v_input->'column5'->>'value', ''),
      nullif(v_input->'column6'->>'value', ''), v_input->'column7'->>'value',
      v_input->'column8'->>'value', v_input->'column9'->>'value',
      v_input->'column25'->>'value', nullif(v_input->'column17'->>'value', '')::bigint,
      bank_account_id, v_input->'column16'->>'value', v_input->'column10'->>'value',
      v_input->'column27'->>'value', 'fio_api'
    ) RETURNING id INTO v_id;
    v_inserted := v_inserted + 1;

    BEGIN
      v_result := public.match_bank_transaction(v_id);
      v_items := v_items || jsonb_build_array(jsonb_build_object(
        'source_id', v_movement_id, 'stored_id', v_id, 'ingest_status', 'inserted',
        'match_verdict', v_result->>'verdict', 'reason', v_result->>'reason'));
    EXCEPTION WHEN OTHERS THEN
      v_items := v_items || jsonb_build_array(jsonb_build_object(
        'source_id', v_movement_id, 'stored_id', v_id, 'ingest_status', 'inserted',
        'match_verdict', 'failed', 'reason', SQLSTATE));
    END;
  END LOOP;

  RETURN jsonb_build_object('inserted', v_inserted, 'skipped', v_skipped, 'items', v_items);
END;
$$;

CREATE INDEX IF NOT EXISTS idx_transaction_id ON eshop.transactions (transaction_id);
REVOKE ALL ON FUNCTION public.insert_transactions(jsonb,bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.insert_transactions(jsonb,bigint) TO service_role;


-- Source: database/functions/eshop_transactions/process_email_transaction.sql
CREATE OR REPLACE FUNCTION public.process_email_transaction(p_data jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_bank_account_id bigint := (p_data->>'bank_account_id')::bigint;
  v_external_id text := nullif(p_data->>'external_id', '');
  v_movement_id bigint := nullif(p_data->>'movement_id', '')::bigint;
  v_command_id bigint := nullif(p_data->>'bank_command_id', '')::bigint;
  v_source text := COALESCE(nullif(p_data->>'ingest_source', ''), 'legacy_email');
  v_existing_id bigint;
  v_id bigint;
  v_match jsonb;
BEGIN
  PERFORM public.require_service_role();
  IF v_source NOT IN ('fio_email', 'airbank_email', 'legacy_email') THEN RAISE EXCEPTION 'EMAIL_SOURCE_INVALID'; END IF;

  UPDATE eshop.bank_accounts SET last_fetch_time = timezone('UTC', now()), updated_at = now()
  WHERE id = v_bank_account_id;

  IF v_external_id IS NOT NULL THEN
    SELECT id INTO v_existing_id FROM eshop.transactions
    WHERE bank_account_id = v_bank_account_id AND external_id = v_external_id;
    IF FOUND THEN
      RETURN jsonb_build_object('ingest_status', 'skipped', 'reason', 'transport_replay',
        'stored_id', v_existing_id, 'match_verdict', 'already_ingested');
    END IF;
  END IF;

  IF v_movement_id IS NOT NULL THEN
    SELECT id INTO v_existing_id FROM eshop.transactions
    WHERE bank_account_id = v_bank_account_id AND transaction_id = v_movement_id;
  ELSIF v_command_id IS NOT NULL THEN
    SELECT min(id) INTO v_existing_id FROM eshop.transactions
    WHERE bank_account_id = v_bank_account_id AND command_id = v_command_id
    HAVING count(*) = 1;
  END IF;

  IF v_existing_id IS NOT NULL THEN
    UPDATE eshop.transactions SET external_id = COALESCE(external_id, v_external_id)
    WHERE id = v_existing_id;
    RETURN jsonb_build_object('ingest_status', 'reconciled', 'stored_id', v_existing_id,
      'match_verdict', 'already_ingested');
  END IF;

  INSERT INTO eshop.transactions (
    bank_account_id, amount, currency, counter_account, bank_code, bank_name,
    vs, ks, ss, message_for_recipient, date, external_id, transaction_id,
    command_id, counter_account_name, payer_reference, ingest_source
  ) VALUES (
    v_bank_account_id, (p_data->>'amount')::numeric, upper(trim(p_data->>'currency')),
    p_data->>'counter_account', p_data->>'bank_code', p_data->>'bank_name',
    nullif(p_data->>'vs', ''), nullif(p_data->>'ks', ''), nullif(p_data->>'ss', ''),
    p_data->>'message', (p_data->>'date')::timestamptz, v_external_id, v_movement_id,
    v_command_id, p_data->>'sender_name', p_data->>'payer_reference', v_source
  ) RETURNING id INTO v_id;

  BEGIN
    v_match := public.match_bank_transaction(v_id);
  EXCEPTION WHEN OTHERS THEN
    v_match := jsonb_build_object('verdict', 'failed', 'reason', SQLSTATE);
  END;
  RETURN jsonb_build_object('ingest_status', 'inserted', 'stored_id', v_id,
    'match_verdict', v_match->>'verdict', 'reason', v_match->>'reason');
END;
$$;

REVOKE ALL ON FUNCTION public.process_email_transaction(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.process_email_transaction(jsonb) TO service_role;


-- Source: database/functions/eshop_transactions/add_transaction_to_payment_info_ws.sql
CREATE OR REPLACE FUNCTION public.add_transaction_to_payment_info_ws(
    p_transaction_id bigint,
    p_payment_info_id bigint
)
RETURNS jsonb SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    bank_acc bigint;
    occasion_id bigint;
BEGIN
    -- Retrieve the associated order_id from payment_info
    SELECT pi.bank_account INTO bank_acc
    FROM eshop.payment_info pi
    WHERE pi.id = p_payment_info_id
    LIMIT 1;

    PERFORM public.check_is_admin_for_bank_account(bank_acc);

    SELECT o.occasion
    INTO occasion_id
    FROM eshop.orders o
    WHERE o.payment_info = p_payment_info_id
    LIMIT 1;

    PERFORM public.check_is_editor_order_on_occasion(occasion_id);

    PERFORM public.apply_transaction_pairing(
      p_transaction_id, p_payment_info_id, 'manual_attach', 'user'
    );

    -- Return success message
    RETURN jsonb_build_object(
        'code', 200,
        'message', 'Transaction added successfully.'
    );

END;
$$ LANGUAGE plpgsql;


-- Source: database/functions/eshop_transactions/insert_manual_transaction.sql
CREATE OR REPLACE FUNCTION public.insert_manual_transaction(
    p_amount double precision,
    p_currency text,
    p_unit_id int,
    p_variable_symbol text,
    p_date text,
    p_note text DEFAULT NULL,
    p_payment_info_id int DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_account_id int;
    v_date timestamp with time zone;
    v_new_transaction_id bigint;
    v_payment_info_id bigint;
    v_candidate_ids bigint[];
BEGIN
    -- Check permissions (must be Unit Manager)
    PERFORM public.check_is_manager_on_unit(p_unit_id);
    v_date := p_date::timestamp with time zone;

    -- 1. Find or Create CASH account
    SELECT ba.id INTO v_account_id
    FROM eshop.bank_accounts ba
    JOIN eshop.unit_bank_accounts uba ON ba.id = uba.bank_account
    WHERE uba.unit = p_unit_id 
      AND ba.type = 'CASH'
      AND p_currency = ANY(ba.supported_currencies);

    IF v_account_id IS NULL THEN
        INSERT INTO eshop.bank_accounts (
            title, type, supported_currencies, account_number, account_number_human_readable
        ) VALUES (
            'Cash Account (' || p_currency || ')', 'CASH', ARRAY[p_currency], '', ''
        )
        RETURNING id INTO v_account_id;

        INSERT INTO eshop.unit_bank_accounts (unit, bank_account, priority)
        VALUES (p_unit_id, v_account_id, 0);
    END IF;

    -- 2. Insert Transaction
    INSERT INTO eshop.transactions (
        bank_account_id,
        amount,
        currency,
        date,
        vs,
        message_for_recipient,
        transaction_type,
        created_by,
        ingest_source
    ) VALUES (
        v_account_id,
        p_amount,
        p_currency,
        v_date,
        p_variable_symbol,
        p_note,
        'manual',
        auth.uid(),
        'manual'
    )
    RETURNING id INTO v_new_transaction_id;

    -- 3. Link to Payment Info & Update Order State
    IF p_payment_info_id IS NOT NULL THEN
         v_payment_info_id := p_payment_info_id;
    ELSIF p_variable_symbol IS NOT NULL AND p_variable_symbol ~ '^[0-9]{1,10}$' THEN
        SELECT array_agg(pi.id ORDER BY pi.id) INTO v_candidate_ids
        FROM eshop.payment_info pi
        JOIN eshop.orders o ON o.payment_info = pi.id
        JOIN public.occasions oc ON oc.id = o.occasion
        WHERE pi.variable_symbol = p_variable_symbol::bigint
          AND upper(trim(pi.currency_code::text)) = upper(trim(p_currency))
          AND oc.unit = p_unit_id;
        IF cardinality(v_candidate_ids) = 1 THEN
          v_payment_info_id := v_candidate_ids[1];
        END IF;
    END IF;

    IF v_payment_info_id IS NOT NULL THEN
        PERFORM public.apply_transaction_pairing(
          v_new_transaction_id, v_payment_info_id, 'manual_insert', 'user'
        );
    END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.insert_manual_transaction(double precision, text, int, text, text, text, int) TO authenticated;


-- Source: database/functions/eshop_transactions/remove_transaction_from_payment_info_ws.sql
CREATE OR REPLACE FUNCTION public.remove_transaction_from_payment_info_ws(
  p_transaction_id bigint,
  p_payment_info_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_bank_account_id bigint;
  v_occasion_id bigint;
BEGIN
  SELECT pi.bank_account, o.occasion INTO v_bank_account_id, v_occasion_id
  FROM eshop.payment_info pi
  JOIN eshop.orders o ON o.payment_info = pi.id
  WHERE pi.id = p_payment_info_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PAYMENT_INFO_NOT_FOUND'; END IF;
  PERFORM public.check_is_admin_for_bank_account(v_bank_account_id);
  PERFORM public.check_is_editor_order_on_occasion(v_occasion_id);
  IF NOT EXISTS (SELECT 1 FROM eshop.transactions t
    WHERE t.id = p_transaction_id AND t.payment_info = p_payment_info_id) THEN
    RAISE EXCEPTION 'TRANSACTION_PAIRING_MISMATCH';
  END IF;
  PERFORM public.apply_transaction_pairing(
    p_transaction_id, NULL, 'manual_unlink', 'user'
  );
END;
$$;


-- Source: database/functions/eshop_transactions/delete_manual_transaction_ws.sql
CREATE OR REPLACE FUNCTION public.delete_manual_transaction_ws(
  p_transaction_id bigint,
  p_payment_info_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_bank_account_id bigint;
  v_occasion_id bigint;
BEGIN
  SELECT pi.bank_account, o.occasion INTO v_bank_account_id, v_occasion_id
  FROM eshop.payment_info pi
  JOIN eshop.orders o ON o.payment_info = pi.id
  WHERE pi.id = p_payment_info_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PAYMENT_INFO_NOT_FOUND'; END IF;
  PERFORM public.check_is_admin_for_bank_account(v_bank_account_id);
  PERFORM public.check_is_editor_order_on_occasion(v_occasion_id);
  IF NOT EXISTS (SELECT 1 FROM eshop.transactions t
    WHERE t.id = p_transaction_id AND t.payment_info = p_payment_info_id
      AND t.transaction_type = 'manual') THEN
    RAISE EXCEPTION 'MANUAL_TRANSACTION_PAIRING_MISMATCH';
  END IF;

  PERFORM public.apply_transaction_pairing(
    p_transaction_id, NULL, 'manual_delete_unlink', 'user'
  );
  INSERT INTO eshop.transaction_pairing_events (
    transaction_snapshot_id, transaction_id, old_payment_info_id,
    new_payment_info_id, action, method, actor_id, actor_kind
  ) VALUES (
    p_transaction_id, p_transaction_id, p_payment_info_id,
    NULL, 'manual_deleted', 'manual_delete', auth.uid(), 'user'
  );
  DELETE FROM eshop.transactions WHERE id = p_transaction_id;
END;
$$;

ALTER TABLE eshop.payment_info DROP CONSTRAINT IF EXISTS payment_info_creditor_reference_check;
ALTER TABLE eshop.payment_info ADD CONSTRAINT payment_info_creditor_reference_check CHECK (
  creditor_reference IS NULL OR (creditor_reference = public.normalize_creditor_reference(creditor_reference)
    AND public.is_valid_creditor_reference(creditor_reference)));
ALTER TABLE eshop.payment_info DROP CONSTRAINT IF EXISTS payment_info_creditor_reference_matches_vs_check;
ALTER TABLE eshop.payment_info ADD CONSTRAINT payment_info_creditor_reference_matches_vs_check CHECK (
  creditor_reference IS NULL OR (variable_symbol IS NOT NULL
    AND creditor_reference = public.generate_creditor_reference(variable_symbol)));
DROP INDEX IF EXISTS eshop.payment_info_creditor_reference_uidx;
CREATE UNIQUE INDEX payment_info_creditor_reference_uidx
  ON eshop.payment_info(bank_account, creditor_reference) WHERE creditor_reference IS NOT NULL;

DROP FUNCTION IF EXISTS public.add_transaction_to_payment_info(bigint,bigint);
DROP FUNCTION IF EXISTS public.update_bank_account(bigint,text,text,text,text[]);
DROP FUNCTION IF EXISTS public.update_bank_account(bigint,text,text,text,text[],text,bigint);
DROP FUNCTION IF EXISTS public.get_my_admin_bank_accounts();
DROP FUNCTION IF EXISTS public.get_bank_accounts_for_unit_management(bigint);


-- Source: database/functions/eshop_bank_accounts/update_bank_account.sql
CREATE OR REPLACE FUNCTION public.update_bank_account(
    p_id bigint,
    p_account_number text,
    p_title text,
    p_type text DEFAULT 'FIO',
    p_supported_currencies text[] DEFAULT NULL,
    p_account_number_human_readable text DEFAULT NULL,
    p_unit_id bigint DEFAULT NULL,
    p_creditor_name text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_id bigint;
    v_account_number text;
BEGIN
    -- Prevent manual manipulation of CASH accounts
    IF p_type = 'CASH' THEN
        RAISE EXCEPTION 'CASH_ACCOUNT_MANUAL_UPDATE_FORBIDDEN';
    END IF;

    -- Input normalization
    v_account_number := TRIM(p_account_number);

    IF p_id IS NULL THEN
        -- Creation: If p_unit_id is provided, enforce that creator is Manager of that unit
        IF p_unit_id IS NOT NULL THEN
             PERFORM check_is_manager_on_unit(p_unit_id);
        END IF;

        -- Check for duplicate account number on insert
        IF EXISTS (SELECT 1 FROM eshop.bank_accounts WHERE account_number = v_account_number) THEN
             RAISE EXCEPTION 'ACCOUNT_NUMBER_EXISTS';
        END IF;

        INSERT INTO eshop.bank_accounts (account_number, title, type, supported_currencies, account_number_human_readable, creditor_name)
        VALUES (v_account_number, p_title, p_type, p_supported_currencies, p_account_number_human_readable, nullif(trim(p_creditor_name), ''))
        RETURNING id INTO v_id;

        -- Automatically make the creator an Admin
        INSERT INTO eshop.bank_account_users (bank_account, "user", is_admin)
        VALUES (v_id, auth.uid(), true);

        -- Automatically link to unit if provided
        IF p_unit_id IS NOT NULL THEN
             INSERT INTO eshop.unit_bank_accounts (unit, bank_account, priority)
             VALUES (p_unit_id, v_id, 0);
        END IF;
    ELSE
        -- Check for duplicate account number on update (exclude current id)
        IF EXISTS (SELECT 1 FROM eshop.bank_accounts WHERE account_number = v_account_number AND id != p_id) THEN
             RAISE EXCEPTION 'ACCOUNT_NUMBER_EXISTS';
        END IF;

        -- Security Check: Caller must be an Admin of the bank account
        IF NOT EXISTS (
            SELECT 1 FROM eshop.bank_account_users 
            WHERE bank_account = p_id AND "user" = auth.uid() AND is_admin = true
        ) THEN
            RAISE EXCEPTION 'Permission denied: Only bank account admins can update details.';
        END IF;

        UPDATE eshop.bank_accounts
        SET
            account_number = v_account_number,
            title = p_title,
            type = p_type,
            supported_currencies = p_supported_currencies,
            account_number_human_readable = p_account_number_human_readable,
            creditor_name = nullif(trim(p_creditor_name), ''),
            updated_at = NOW()
        WHERE id = p_id
        RETURNING id INTO v_id;
    END IF;
    RETURN v_id;
END;
$$;


-- Source: database/functions/eshop_bank_accounts/get_my_admin_bank_accounts.sql
CREATE OR REPLACE FUNCTION public.get_my_admin_bank_accounts()
RETURNS TABLE (
    id bigint,
    account_number text,
    account_number_human_readable text,
    title text,
    creditor_name text,
    type text,
    token_masked text,
    token_expiry_date timestamptz,
    supported_currencies text[],
    linked_units text[],
    last_fetch_time timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
    RETURN QUERY
    SELECT
        ba.id,
        ba.account_number,
        ba.account_number_human_readable,
        ba.title,
        ba.creditor_name,
        ba.type,
        CASE WHEN s.secret IS NULL THEN NULL
             WHEN length(s.secret) <= 4 THEN '************'
             ELSE '************' || right(s.secret, 4)
        END as token_masked,
        s.expiry_date as token_expiry_date,
        ba.supported_currencies,
        ARRAY(
            SELECT u.title 
            FROM eshop.unit_bank_accounts uba
            JOIN public.units u ON uba.unit = u.id
            WHERE uba.bank_account = ba.id
        ) as linked_units,
        ba.last_fetch_time
    FROM eshop.bank_accounts ba
    JOIN eshop.bank_account_users bau ON ba.id = bau.bank_account
    LEFT JOIN eshop.secrets s ON ba.secret = s.id
    WHERE bau."user" = auth.uid() AND bau.is_admin = true
    AND ba.type != 'cash'
    ORDER BY ba.title;
END;
$$;


-- Source: database/functions/eshop_bank_accounts/get_bank_accounts_for_unit_management.sql
CREATE OR REPLACE FUNCTION get_bank_accounts_for_unit_management(p_unit_id bigint)
RETURNS TABLE (
    id bigint,
    account_number text,
    title text,
    creditor_name text,
    type text,
    is_admin boolean,
    token_masked text,
    token_expiry_date timestamptz,
    supported_currencies text[]
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ba.id,
        ba.account_number,
        ba.title,
        ba.creditor_name,
        ba.type,
        EXISTS (
            SELECT 1 
            FROM eshop.bank_account_users bau
            WHERE bau.bank_account = ba.id 
            AND bau."user" = auth.uid() 
            AND bau.is_admin = true
        ) as is_admin,
        CASE 
            WHEN s.secret IS NOT NULL THEN 
                '************' || right(s.secret, 4)
            ELSE NULL 
        END as token_masked,
        s.expiry_date as token_expiry_date,
        ba.supported_currencies
    FROM eshop.bank_accounts ba
    JOIN eshop.unit_bank_accounts uba ON ba.id = uba.bank_account
    LEFT JOIN eshop.secrets s ON ba.secret = s.id
    WHERE uba.unit = p_unit_id
    AND ba.type != 'CASH'; -- Exclude Cash Accounts from management list
END;
$$;

REVOKE ALL ON FUNCTION public.update_bank_account(bigint,text,text,text,text[],text,bigint,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.update_bank_account(bigint,text,text,text,text[],text,bigint,text) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.add_transaction_to_payment_info_ws(bigint,bigint) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.add_transaction_to_payment_info_ws(bigint,bigint) TO authenticated;
REVOKE ALL ON FUNCTION public.insert_manual_transaction(double precision,text,integer,text,text,text,integer) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.insert_manual_transaction(double precision,text,integer,text,text,text,integer) TO authenticated;
REVOKE ALL ON FUNCTION public.remove_transaction_from_payment_info_ws(bigint,bigint) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.remove_transaction_from_payment_info_ws(bigint,bigint) TO authenticated;
REVOKE ALL ON FUNCTION public.delete_manual_transaction_ws(bigint,bigint) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.delete_manual_transaction_ws(bigint,bigint) TO authenticated;
REVOKE ALL ON FUNCTION public.get_my_admin_bank_accounts() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_my_admin_bank_accounts() TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.get_bank_accounts_for_unit_management(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_bank_accounts_for_unit_management(bigint) TO authenticated,service_role;
