-- =============================================================================
-- Migration: Speakers & Counseling (speakers feature) — Phase 1 (SQL)
--
-- Adds the 4 new tables (speakers, speaker_topics, speaker_topic_links,
-- event_speakers) with RLS + SELECT-only policies + moddatetime triggers, and
-- all speaker/counseling RPCs, plus the modified sign_user_to_event (counseling
-- branch) and the relocated search_occasion_content (excludes counseling slots).
--
-- Idempotent: CREATE TABLE IF NOT EXISTS, DROP POLICY/TRIGGER IF EXISTS,
-- CREATE OR REPLACE FUNCTION throughout.
--
-- !!! DO NOT APPLY TO LIVE YET. The Flutter client and admin/user UI that drive
-- these RPCs are not implemented; this migration is committed alongside Phase 1
-- and deployed only once the full feature is ready (see plan section 8).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- (1) Tables + indexes (authoritative DDL: database/tables/tables.sql §12)
-- ---------------------------------------------------------------------------

create table if not exists public.speakers (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  occasion    BIGINT NOT NULL,
  title       TEXT NOT NULL,
  subtitle    TEXT NULL,
  description TEXT NULL,
  image       TEXT NULL,
  "order"     BIGINT NOT NULL DEFAULT 0,
  is_hidden   BOOLEAN NOT NULL DEFAULT false,
  data        JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT speakers_pkey PRIMARY KEY (id),
  CONSTRAINT speakers_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id) ON DELETE CASCADE,
  CONSTRAINT speakers_title_length_check CHECK (char_length(title) <= 200)
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS speakers_occasion_idx ON public.speakers (occasion);

create table if not exists public.speaker_topics (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  occasion    BIGINT NOT NULL,
  code        TEXT NULL,
  title       TEXT NOT NULL,
  "order"     BIGINT NOT NULL DEFAULT 0,
  is_hidden   BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT speaker_topics_pkey PRIMARY KEY (id),
  CONSTRAINT speaker_topics_occasion_fkey FOREIGN KEY (occasion) REFERENCES public.occasions (id) ON DELETE CASCADE
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS speaker_topics_occasion_idx ON public.speaker_topics (occasion);
CREATE UNIQUE INDEX IF NOT EXISTS speaker_topics_occasion_code_uidx
  ON public.speaker_topics (occasion, code) WHERE (code IS NOT NULL);

create table if not exists public.speaker_topic_links (
  speaker BIGINT NOT NULL,
  topic   BIGINT NOT NULL,
  CONSTRAINT speaker_topic_links_pkey PRIMARY KEY (speaker, topic),
  CONSTRAINT speaker_topic_links_speaker_fkey FOREIGN KEY (speaker) REFERENCES public.speakers (id) ON DELETE CASCADE,
  CONSTRAINT speaker_topic_links_topic_fkey FOREIGN KEY (topic) REFERENCES public.speaker_topics (id) ON DELETE CASCADE
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS speaker_topic_links_topic_idx ON public.speaker_topic_links (topic);

create table if not exists public.event_speakers (
  event   BIGINT NOT NULL,
  speaker BIGINT NOT NULL,
  CONSTRAINT event_speakers_pkey PRIMARY KEY (event, speaker),
  CONSTRAINT event_speakers_event_fkey FOREIGN KEY (event) REFERENCES public.events (id) ON DELETE CASCADE,
  CONSTRAINT event_speakers_speaker_fkey FOREIGN KEY (speaker) REFERENCES public.speakers (id) ON DELETE CASCADE
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS event_speakers_speaker_idx ON public.event_speakers (speaker);

-- ---------------------------------------------------------------------------
-- (2) RLS: enable + SELECT-only policies (all writes go through the RPCs)
-- ---------------------------------------------------------------------------

ALTER TABLE public.speakers            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.speaker_topics      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.speaker_topic_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_speakers      ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable select for all" ON public.speakers;
CREATE POLICY "Enable select for all" ON public.speakers FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable select for all" ON public.speaker_topics;
CREATE POLICY "Enable select for all" ON public.speaker_topics FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable select for all" ON public.speaker_topic_links;
CREATE POLICY "Enable select for all" ON public.speaker_topic_links FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable select for all" ON public.event_speakers;
CREATE POLICY "Enable select for all" ON public.event_speakers FOR SELECT USING (true);

-- ---------------------------------------------------------------------------
-- (3) moddatetime updated_at triggers (speakers, speaker_topics)
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS handle_updated_at ON public.speakers;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.speakers
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
DROP TRIGGER IF EXISTS handle_updated_at ON public.speaker_topics;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.speaker_topics
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

-- ---------------------------------------------------------------------------
-- (4) Functions
-- ---------------------------------------------------------------------------

-- ===== get_is_speakers_enabled_on_occasion =====
CREATE OR REPLACE FUNCTION get_is_speakers_enabled_on_occasion(p_occasion BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.occasions o
    CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.features, '[]'::jsonb)) feature
    WHERE o.id = p_occasion
      AND feature->>'code' = 'speakers'
      AND LOWER(COALESCE(feature->>'is_enabled', 'false')) = 'true'
  );
$$;

-- ===== get_speakers =====
CREATE OR REPLACE FUNCTION get_speakers(
    p_occasion            BIGINT,
    p_include_description BOOLEAN DEFAULT FALSE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    speakersData      JSONB;
    topicsData        JSONB;
    topicLinksData    JSONB;
    eventSpeakersData JSONB;
BEGIN
    -- (a) visible speakers, description only on request (payload size)
    SELECT jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
        'id',          s.id,
        'title',       s.title,
        'subtitle',    s.subtitle,
        'description', CASE WHEN p_include_description THEN s.description ELSE NULL END,
        'image',       s.image,
        'order',       s."order",
        'updated_at',  s.updated_at
    )) ORDER BY s."order", s.title)
    INTO speakersData
    FROM public.speakers s
    WHERE s.occasion = p_occasion
      AND s.is_hidden = FALSE;

    -- (b) visible topic catalog
    SELECT jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
        'id',    t.id,
        'code',  t.code,
        'title', t.title,
        'order', t."order"
    )) ORDER BY t."order", t.title)
    INTO topicsData
    FROM public.speaker_topics t
    WHERE t.occasion = p_occasion
      AND t.is_hidden = FALSE;

    -- (c) competence links restricted to visible speakers and topics
    SELECT jsonb_agg(jsonb_build_object(
        'speaker', stl.speaker,
        'topic',   stl.topic
    ))
    INTO topicLinksData
    FROM public.speaker_topic_links stl
    JOIN public.speakers s ON s.id = stl.speaker
    JOIN public.speaker_topics t ON t.id = stl.topic
    WHERE s.occasion = p_occasion AND s.is_hidden = FALSE
      AND t.occasion = p_occasion AND t.is_hidden = FALSE;

    -- (d) event links restricted to visible speakers and non-hidden events
    SELECT jsonb_agg(jsonb_build_object(
        'event',   es.event,
        'speaker', es.speaker
    ))
    INTO eventSpeakersData
    FROM public.event_speakers es
    JOIN public.speakers s ON s.id = es.speaker
    JOIN public.events e ON e.id = es.event
    WHERE s.occasion = p_occasion AND s.is_hidden = FALSE
      AND e.occasion = p_occasion AND e.is_hidden = FALSE;

    RETURN jsonb_build_object(
      'code', 200,
      'data', jsonb_build_object(
        'speakers',            COALESCE(speakersData,      '[]'::jsonb),
        'speaker_topics',      COALESCE(topicsData,        '[]'::jsonb),
        'speaker_topic_links', COALESCE(topicLinksData,    '[]'::jsonb),
        'event_speakers',      COALESCE(eventSpeakersData, '[]'::jsonb)
      )
    );
END;
$$;

-- ===== update_speaker =====
CREATE OR REPLACE FUNCTION update_speaker(p_occasion BIGINT, p_speaker JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_speaker_id BIGINT;
    v_row        public.speakers%ROWTYPE;
    v_title      TEXT;
BEGIN
    -- Only editors of the occasion may write speakers.
    IF NOT public.get_is_editor_on_occasion(p_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    IF p_speaker ? 'id' AND (p_speaker->>'id') IS NOT NULL THEN
        -- UPDATE — guarded by occasion to prevent cross-occasion edits.
        v_speaker_id := (p_speaker->>'id')::BIGINT;

        UPDATE public.speakers s SET
            title       = COALESCE(p_speaker->>'title', s.title),
            subtitle    = CASE WHEN p_speaker ? 'subtitle'    THEN p_speaker->>'subtitle'              ELSE s.subtitle    END,
            description = CASE WHEN p_speaker ? 'description'  THEN p_speaker->>'description'           ELSE s.description END,
            image       = CASE WHEN p_speaker ? 'image'       THEN p_speaker->>'image'                 ELSE s.image       END,
            "order"     = CASE WHEN p_speaker ? 'order'       THEN (p_speaker->>'order')::BIGINT       ELSE s."order"     END,
            is_hidden   = CASE WHEN p_speaker ? 'is_hidden'   THEN (p_speaker->>'is_hidden')::BOOLEAN  ELSE s.is_hidden   END,
            data        = CASE WHEN p_speaker ? 'data'        THEN p_speaker->'data'                   ELSE s.data        END
        WHERE s.id = v_speaker_id AND s.occasion = p_occasion
        RETURNING s.* INTO v_row;

        IF NOT FOUND THEN
            RETURN jsonb_build_object('code', 404);
        END IF;
    ELSE
        -- INSERT — a non-empty title is required.
        v_title := p_speaker->>'title';
        IF v_title IS NULL OR btrim(v_title) = '' THEN
            RETURN jsonb_build_object('code', 400);
        END IF;

        INSERT INTO public.speakers (occasion, title, subtitle, description, image, "order", is_hidden, data)
        VALUES (
            p_occasion,
            v_title,
            p_speaker->>'subtitle',
            p_speaker->>'description',
            p_speaker->>'image',
            COALESCE((p_speaker->>'order')::BIGINT, 0),
            COALESCE((p_speaker->>'is_hidden')::BOOLEAN, FALSE),
            COALESCE(p_speaker->'data', '{}'::jsonb)
        )
        RETURNING * INTO v_row;

        v_speaker_id := v_row.id;
    END IF;

    -- Atomically replace competence links when a 'topics' array is supplied
    -- (may be empty). Only topics of this occasion are accepted; foreign or
    -- unknown ids are silently ignored.
    IF p_speaker ? 'topics' THEN
        DELETE FROM public.speaker_topic_links WHERE speaker = v_speaker_id;

        INSERT INTO public.speaker_topic_links (speaker, topic)
        SELECT v_speaker_id, t.id
        FROM public.speaker_topics t
        WHERE t.occasion = p_occasion
          AND t.id IN (
            SELECT elem::BIGINT
            FROM jsonb_array_elements_text(p_speaker->'topics') AS elem
          );
    END IF;

    RETURN jsonb_build_object(
        'code', 200,
        'data', to_jsonb(v_row) || jsonb_build_object(
            'topics', COALESCE((
                SELECT jsonb_agg(stl.topic ORDER BY stl.topic)
                FROM public.speaker_topic_links stl
                WHERE stl.speaker = v_speaker_id
            ), '[]'::jsonb)
        )
    );
END;
$$;

-- ===== delete_speaker =====
CREATE OR REPLACE FUNCTION delete_speaker(p_speaker_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_occasion BIGINT;
BEGIN
    SELECT occasion INTO v_occasion
    FROM public.speakers
    WHERE id = p_speaker_id;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    IF NOT public.get_is_editor_on_occasion(v_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    -- speaker_topic_links and event_speakers cascade. Generated slot events
    -- intentionally remain (they are ordinary events).
    DELETE FROM public.speakers WHERE id = p_speaker_id;

    RETURN jsonb_build_object('code', 200);
END;
$$;

-- ===== update_speaker_topic =====
CREATE OR REPLACE FUNCTION update_speaker_topic(p_occasion BIGINT, p_topic JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_topic_id BIGINT;
    v_row      public.speaker_topics%ROWTYPE;
    v_title    TEXT;
BEGIN
    -- Only editors of the occasion may write the topic catalog.
    IF NOT public.get_is_editor_on_occasion(p_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    IF p_topic ? 'id' AND (p_topic->>'id') IS NOT NULL THEN
        -- UPDATE — guarded by occasion to prevent cross-occasion edits.
        v_topic_id := (p_topic->>'id')::BIGINT;

        UPDATE public.speaker_topics t SET
            code      = CASE WHEN p_topic ? 'code'      THEN p_topic->>'code'                  ELSE t.code      END,
            title     = COALESCE(p_topic->>'title', t.title),
            "order"   = CASE WHEN p_topic ? 'order'     THEN (p_topic->>'order')::BIGINT        ELSE t."order"   END,
            is_hidden = CASE WHEN p_topic ? 'is_hidden' THEN (p_topic->>'is_hidden')::BOOLEAN   ELSE t.is_hidden END
        WHERE t.id = v_topic_id AND t.occasion = p_occasion
        RETURNING t.* INTO v_row;

        IF NOT FOUND THEN
            RETURN jsonb_build_object('code', 404);
        END IF;
    ELSE
        -- INSERT — a non-empty title is required.
        v_title := p_topic->>'title';
        IF v_title IS NULL OR btrim(v_title) = '' THEN
            RETURN jsonb_build_object('code', 400);
        END IF;

        INSERT INTO public.speaker_topics (occasion, code, title, "order", is_hidden)
        VALUES (
            p_occasion,
            p_topic->>'code',
            v_title,
            COALESCE((p_topic->>'order')::BIGINT, 0),
            COALESCE((p_topic->>'is_hidden')::BOOLEAN, FALSE)
        )
        RETURNING * INTO v_row;
    END IF;

    RETURN jsonb_build_object('code', 200, 'data', to_jsonb(v_row));
EXCEPTION
    WHEN unique_violation THEN
        -- (occasion, code) must be unique.
        RETURN jsonb_build_object('code', 400);
END;
$$;

-- ===== delete_speaker_topic =====
CREATE OR REPLACE FUNCTION delete_speaker_topic(p_topic_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_occasion BIGINT;
BEGIN
    SELECT occasion INTO v_occasion
    FROM public.speaker_topics
    WHERE id = p_topic_id;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    IF NOT public.get_is_editor_on_occasion(v_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    -- speaker_topic_links cascade.
    DELETE FROM public.speaker_topics WHERE id = p_topic_id;

    RETURN jsonb_build_object('code', 200);
END;
$$;

-- ===== set_event_speakers =====
CREATE OR REPLACE FUNCTION set_event_speakers(p_event BIGINT, p_speakers BIGINT[])
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_occasion BIGINT;
    v_speakers BIGINT[] := COALESCE(p_speakers, ARRAY[]::BIGINT[]);
BEGIN
    SELECT occasion INTO v_occasion
    FROM public.events
    WHERE id = p_event;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    IF NOT public.get_is_editor_on_occasion(v_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    -- Every supplied speaker must belong to the event's occasion.
    IF EXISTS (
        SELECT 1
        FROM unnest(v_speakers) AS sid
        LEFT JOIN public.speakers s ON s.id = sid AND s.occasion = v_occasion
        WHERE s.id IS NULL
    ) THEN
        RETURN jsonb_build_object('code', 400);
    END IF;

    -- Replace the set: drop links no longer present, add the missing ones.
    DELETE FROM public.event_speakers
    WHERE event = p_event
      AND speaker <> ALL (v_speakers);

    INSERT INTO public.event_speakers (event, speaker)
    SELECT p_event, sid
    FROM unnest(v_speakers) AS sid
    ON CONFLICT (event, speaker) DO NOTHING;

    RETURN jsonb_build_object('code', 200);
END;
$$;

-- ===== get_speakers_for_edit =====
CREATE OR REPLACE FUNCTION get_speakers_for_edit(p_occasion BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_speakers JSONB;
    v_topics   JSONB;
BEGIN
    -- Admin read: all speakers and topics, including hidden.
    IF NOT public.get_is_editor_view_on_occasion(p_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    -- Speakers (all columns) + competence topic ids + linked events with
    -- occupancy. Ordered by "order", title.
    SELECT COALESCE(jsonb_agg(q.sp ORDER BY q.sp_order, q.sp_title), '[]'::jsonb)
    INTO v_speakers
    FROM (
        SELECT
            to_jsonb(s) || jsonb_build_object(
                'topics', COALESCE((
                    SELECT jsonb_agg(stl.topic ORDER BY stl.topic)
                    FROM public.speaker_topic_links stl
                    WHERE stl.speaker = s.id
                ), '[]'::jsonb),
                'events', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                        'id',                 e.id,
                        'title',              e.title,
                        'start_time',         e.start_time,
                        'end_time',           e.end_time,
                        'max_participants',   e.max_participants,
                        'occupied',           (SELECT count(*) FROM public.event_users eu WHERE eu.event = e.id),
                        'is_counseling_slot', COALESCE((e.data->>'is_counseling_slot')::boolean, FALSE)
                    ) ORDER BY e.start_time)
                    FROM public.event_speakers es
                    JOIN public.events e ON e.id = es.event
                    WHERE es.speaker = s.id
                ), '[]'::jsonb)
            ) AS sp,
            s."order" AS sp_order,
            s.title   AS sp_title
        FROM public.speakers s
        WHERE s.occasion = p_occasion
    ) q;

    -- Full topic catalog, including hidden.
    SELECT COALESCE(jsonb_agg(to_jsonb(t) ORDER BY t."order", t.title), '[]'::jsonb)
    INTO v_topics
    FROM public.speaker_topics t
    WHERE t.occasion = p_occasion;

    RETURN jsonb_build_object(
        'code', 200,
        'data', jsonb_build_object(
            'speakers',       v_speakers,
            'speaker_topics', v_topics
        )
    );
END;
$$;

-- ===== create_counseling_slots =====
CREATE OR REPLACE FUNCTION create_counseling_slots(
    p_speaker       BIGINT,
    p_start         TIMESTAMPTZ,
    p_end           TIMESTAMPTZ,
    p_slot_minutes  INT,
    p_place         BIGINT DEFAULT NULL,
    p_capacity      INT DEFAULT 1,
    p_title         TEXT DEFAULT NULL,
    p_break_minutes INT DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_occasion      BIGINT;
    v_speaker_title TEXT;
    v_type          TEXT;
    v_title         TEXT;
    v_slot_start    TIMESTAMPTZ;
    v_slot_end      TIMESTAMPTZ;
    v_event_id      BIGINT;
    v_ids           BIGINT[] := ARRAY[]::BIGINT[];
    v_count         INT := 0;
BEGIN
    SELECT occasion, title INTO v_occasion, v_speaker_title
    FROM public.speakers
    WHERE id = p_speaker;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    IF NOT public.get_is_editor_on_occasion(v_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    -- Parameter validation.
    IF p_slot_minutes IS NULL OR p_slot_minutes < 5
       OR p_start IS NULL OR p_end IS NULL OR p_start >= p_end
       OR p_capacity IS NULL OR p_capacity < 1
       OR p_break_minutes IS NULL OR p_break_minutes < 0 THEN
        RETURN jsonb_build_object('code', 400);
    END IF;

    IF p_place IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.places
            WHERE id = p_place AND occasion = v_occasion
        ) THEN
            RETURN jsonb_build_object('code', 400);
        END IF;
    END IF;

    -- Event type comes from the "speakers" feature config (default 'counseling').
    SELECT COALESCE(elem->>'counseling_event_type', 'counseling')
    INTO v_type
    FROM public.occasions o
    CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.features, '[]'::jsonb)) elem
    WHERE o.id = v_occasion AND elem->>'code' = 'speakers'
    LIMIT 1;

    IF v_type IS NULL THEN
        v_type := 'counseling';
    END IF;

    v_title := COALESCE(p_title, v_speaker_title);

    -- Generate slots: last slot must fully fit within [p_start, p_end].
    v_slot_start := p_start;
    WHILE v_slot_start + make_interval(mins => p_slot_minutes) <= p_end LOOP
        v_slot_end := v_slot_start + make_interval(mins => p_slot_minutes);

        INSERT INTO public.events (occasion, title, start_time, end_time, max_participants, place, type, is_hidden, data)
        VALUES (
            v_occasion,
            v_title,
            v_slot_start,
            v_slot_end,
            p_capacity,
            p_place,
            v_type,
            FALSE,
            jsonb_build_object('is_counseling_slot', true)
        )
        RETURNING id INTO v_event_id;

        INSERT INTO public.event_speakers (event, speaker) VALUES (v_event_id, p_speaker);

        v_ids := array_append(v_ids, v_event_id);
        v_count := v_count + 1;

        v_slot_start := v_slot_start + make_interval(mins => p_slot_minutes + p_break_minutes);
    END LOOP;

    RETURN jsonb_build_object(
        'code', 200,
        'data', jsonb_build_object(
            'created',   v_count,
            'event_ids', to_jsonb(v_ids)
        )
    );
END;
$$;

-- ===== delete_empty_counseling_slots =====
CREATE OR REPLACE FUNCTION delete_empty_counseling_slots(p_speaker BIGINT, p_from TIMESTAMPTZ DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_occasion BIGINT;
    v_deleted  INT;
BEGIN
    SELECT occasion INTO v_occasion
    FROM public.speakers
    WHERE id = p_speaker;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    IF NOT public.get_is_editor_on_occasion(v_occasion) THEN
        RETURN jsonb_build_object('code', 403);
    END IF;

    -- Clear the saved-events rows first: event_users_saved has an FK to events
    -- with no ON DELETE CASCADE, so it would otherwise block the delete.
    DELETE FROM public.event_users_saved
    WHERE event IN (
        SELECT e.id
        FROM public.events e
        JOIN public.event_speakers es ON es.event = e.id
        WHERE es.speaker = p_speaker
          AND (e.data->>'is_counseling_slot')::boolean IS TRUE
          AND (p_from IS NULL OR e.start_time >= p_from)
          AND NOT EXISTS (SELECT 1 FROM public.event_users eu WHERE eu.event = e.id)
    );

    -- Delete only empty slots; occupied slots (any event_users row) survive.
    DELETE FROM public.events e
    USING public.event_speakers es
    WHERE es.event = e.id
      AND es.speaker = p_speaker
      AND (e.data->>'is_counseling_slot')::boolean IS TRUE
      AND (p_from IS NULL OR e.start_time >= p_from)
      AND NOT EXISTS (SELECT 1 FROM public.event_users eu WHERE eu.event = e.id);

    GET DIAGNOSTICS v_deleted = ROW_COUNT;

    RETURN jsonb_build_object(
        'code', 200,
        'data', jsonb_build_object('deleted', v_deleted)
    );
END;
$$;

-- ===== get_counseling_availability =====
CREATE OR REPLACE FUNCTION get_counseling_availability(p_occasion BIGINT, p_topic BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_uid        UUID := auth.uid();
    v_counselors JSONB;
BEGIN
    -- Feature gate.
    IF NOT public.get_is_speakers_enabled_on_occasion(p_occasion) THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    -- The chosen topic must belong to the occasion and be visible.
    -- NOTE (decision R3): the topic is only a filter — it is never stored.
    IF NOT EXISTS (
        SELECT 1 FROM public.speaker_topics t
        WHERE t.id = p_topic AND t.occasion = p_occasion AND t.is_hidden = FALSE
    ) THEN
        RETURN jsonb_build_object('code', 404);
    END IF;

    SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
            'id',       s.id,
            'title',    s.title,
            'subtitle', s.subtitle,
            'image',    s.image,
            'slots', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                    'id',               e.id,
                    'start_time',       e.start_time,
                    'end_time',         e.end_time,
                    'place',            e.place,
                    'max_participants', e.max_participants,
                    'occupied',         (SELECT count(*) FROM public.event_users eu WHERE eu.event = e.id),
                    'isSignedIn',       (v_uid IS NOT NULL AND EXISTS (
                                            SELECT 1 FROM public.event_users eu2
                                            WHERE eu2.event = e.id AND eu2."user" = v_uid))
                ) ORDER BY e.start_time)
                FROM public.event_speakers es
                JOIN public.events e ON e.id = es.event
                WHERE es.speaker = s.id
                  AND e.occasion = p_occasion
                  AND (e.data->>'is_counseling_slot')::boolean IS TRUE
                  AND e.end_time > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
            ), '[]'::jsonb)
        ) ORDER BY s."order", s.title
    ), '[]'::jsonb)
    INTO v_counselors
    FROM public.speakers s
    JOIN public.speaker_topic_links stl ON stl.speaker = s.id AND stl.topic = p_topic
    WHERE s.occasion = p_occasion AND s.is_hidden = FALSE;

    RETURN jsonb_build_object(
        'code', 200,
        'data', jsonb_build_object('counselors', v_counselors)
    );
END;
$$;

-- ===== sign_user_to_event (modified: counseling branch) =====
create or replace function sign_user_to_event (ev bigint, usr uuid) returns jsonb
 language plpgsql
 SECURITY DEFINER
SET search_path = public, extensions
 as $$
declare
  i_max_participants integer;
  current_participants integer;
  event_group_count integer;
  event_group integer;
  exclusive_event_count integer;
  already_in_count integer;
  current_men_participants integer;
  current_women_participants integer;
  b_split_for_men_women boolean;
  is_current_user_male boolean;

  registration_start timestamp;
  event_start_time timestamp;
  event_end_time timestamp;
  workshops_feature jsonb;
  e RECORD;

  v_occasion bigint;
  v_is_counseling boolean;
  speakers_feature jsonb;
  v_limit integer;
  v_active integer;

begin

  -- Check if the user already exists on the occasion
  IF (SELECT get_exists_on_occasion_user(usr, (SELECT occasion FROM events WHERE id = ev))) <> TRUE THEN

      -- Check if the occasion is open
      IF (SELECT is_open FROM occasions WHERE id = (SELECT occasion FROM events WHERE id = ev)) = TRUE THEN

          -- Add the user to the occasion
          PERFORM add_user_to_occasion((SELECT occasion FROM events WHERE id = ev), usr);

          -- Recheck if the user now exists on the occasion
          IF (SELECT get_exists_on_occasion_user(usr, (SELECT occasion FROM events WHERE id = ev))) <> TRUE THEN
              -- If user still doesn't exist, return a 403 response
              RETURN json_build_object('code', 403, 'message', 'Failed to add user to occasion');
          END IF;
      ELSE
          -- If the occasion is not open, return a 403 response
          RETURN json_build_object('code', 403, 'message', 'Occasion is not open');
      END IF;
  END IF;

  IF auth.uid() <> usr THEN
      IF NOT EXISTS (
        SELECT 1 FROM user_companions WHERE "user" = auth.uid() AND companion = usr) THEN
          IF (SELECT get_is_editor_on_occasion((SELECT occasion FROM events WHERE id = ev))) <> TRUE THEN
            RETURN json_build_object('code', 403);
          END IF;
      END IF;
  END IF;

  -- Resolve the occasion and detect whether this event is a counseling slot.
  SELECT occasion, (data->>'is_counseling_slot')::boolean IS TRUE
    INTO v_occasion, v_is_counseling
  FROM events
  WHERE id = ev;

  IF v_is_counseling THEN
    -- Counseling slots use their own registration window from the "speakers"
    -- feature; the workshops gate (104/108) does not apply (decision R1).
    SELECT elem
      INTO speakers_feature
    FROM occasions,
         jsonb_array_elements(features) elem
    WHERE id = v_occasion
      AND elem->>'code' = 'speakers'
    LIMIT 1;

    -- (a) Feature must be present and enabled, else registration is closed.
    IF speakers_feature IS NULL
       OR (speakers_feature->>'is_enabled')::boolean IS NOT TRUE THEN
      RETURN json_build_object('code', 108);
    END IF;

    registration_start := (speakers_feature->>'registration_start_time')::timestamp;
    IF registration_start IS NOT NULL THEN
      IF CURRENT_TIMESTAMP AT TIME ZONE 'UTC' < registration_start THEN
        RETURN json_build_object('code', 104, 'events_registration_start', registration_start AT TIME ZONE 'UTC');
      END IF;
    END IF;

    -- (b) Limit of the user's future counseling bookings (0 = unlimited).
    v_limit := COALESCE((speakers_feature->>'max_active_bookings')::int, 1);
    IF v_limit > 0 THEN
      SELECT count(*)
        INTO v_active
      FROM event_users eu
      JOIN events e2 ON e2.id = eu.event
      WHERE eu."user" = usr
        AND e2.occasion = v_occasion
        AND (e2.data->>'is_counseling_slot')::boolean IS TRUE
        AND e2.end_time > CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
      IF v_active >= v_limit THEN
        RETURN json_build_object('code', 109);
      END IF;
    END IF;
  ELSE
    -- Check registration start time from occasions.features for the "workshops" feature
    SELECT elem
    INTO workshops_feature
    FROM occasions,
         jsonb_array_elements(features) elem
    WHERE id = (SELECT occasion FROM events WHERE id = ev)
      AND elem->>'code' = 'workshops'
    LIMIT 1;

    IF workshops_feature IS NOT NULL THEN
      -- If the workshops feature is not enabled, do not allow sign in
      IF (workshops_feature->>'is_enabled')::boolean IS NOT TRUE THEN
        RETURN json_build_object('code', 108, 'message', 'Registration for workshops is not enabled');
      END IF;
      -- If start_time is provided, enforce registration start time
      registration_start := (workshops_feature->>'start_time')::timestamp;
      IF registration_start IS NOT NULL THEN
        IF CURRENT_TIMESTAMP AT TIME ZONE 'UTC' < registration_start THEN
          RETURN json_build_object('code', 104, 'events_registration_start', registration_start AT TIME ZONE 'UTC');
        END IF;
      END IF;
    END IF;
    -- If the workshops feature is not present or its start_time is null, sign in is enabled
  END IF;

  SELECT start_time, end_time INTO event_start_time, event_end_time
  FROM events
  WHERE id = ev;

  IF CURRENT_TIMESTAMP AT TIME ZONE 'UTC' > event_end_time THEN
    RETURN json_build_object('code', 100);
  END IF;

  SELECT count(*) FROM event_users eu WHERE eu.event = ev AND eu."user" = usr INTO already_in_count;
  IF already_in_count > 0 THEN
    RETURN json_build_object('code', 103);
  END IF;

  SELECT count(*) FROM exclusive_events WHERE event = ev INTO event_group_count;
  IF event_group_count > 0 THEN
    SELECT "group" FROM exclusive_events WHERE event = ev INTO event_group;
    SELECT count(*) FROM exclusive_events ee JOIN event_users eu ON ee.event = eu.event
      WHERE ee."group" = event_group AND eu."user" = usr INTO exclusive_event_count;
    IF exclusive_event_count > 0 THEN
      RETURN json_build_object('code', 102);
    END IF;
  END IF;

  -- Check if the event already has the maximum number of participants
  SELECT max_participants FROM events WHERE id = ev INTO i_max_participants;
  SELECT split_for_men_women FROM events WHERE id = ev INTO b_split_for_men_women;

  IF b_split_for_men_women THEN
    SELECT exists (SELECT sex FROM user_info WHERE id = usr AND sex = 'male') INTO is_current_user_male;
    SELECT count(*) FROM event_users eu JOIN user_info ei ON eu."user" = ei.id
      WHERE event = ev AND ei.sex = 'male' INTO current_men_participants;
    SELECT count(*) FROM event_users eu JOIN user_info ei ON eu."user" = ei.id
      WHERE event = ev AND ei.sex <> 'male' INTO current_women_participants;
    IF is_current_user_male AND current_men_participants >= (i_max_participants / 2) THEN
      RETURN json_build_object('code', 105);
    ELSIF NOT is_current_user_male AND current_women_participants >= (i_max_participants / 2) THEN
      RETURN json_build_object('code', 106);
    END IF;
  END IF;

  -- Loop through user_events to check for scheduling conflicts
  FOR e IN
      SELECT events.id, events.start_time, events.end_time
      FROM events
      JOIN event_users ON events.id = event_users.event
      WHERE event_users."user" = usr
  LOOP
      IF ((e.start_time < event_end_time AND e.start_time > event_start_time) OR
          (e.end_time < event_end_time AND e.end_time > event_start_time) OR
          (e.start_time = event_start_time) OR
          (e.end_time = event_end_time)) THEN
          RETURN json_build_object('code', 107);
      END IF;
  END LOOP;

  SELECT count(*) FROM event_users WHERE event = ev INTO current_participants;
  IF current_participants >= i_max_participants THEN
    RETURN json_build_object('code', 101);
  ELSE
    INSERT INTO event_users (event, "user") VALUES (ev, usr);
    RETURN json_build_object('code', 200);
  END IF;
END;
$$;

-- ===== search_occasion_content (relocated: excludes counseling slots) =====
CREATE OR REPLACE FUNCTION public.search_occasion_content(p_occasion bigint, p_query text, p_limit integer DEFAULT 50)
 RETURNS TABLE(entity_type text, entity_id bigint, title text, snippet text, rank real, start_time timestamp with time zone, parent_id bigint, extra jsonb)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
    v_features        JSONB;
    v_norm_query      TEXT;
    v_effective_limit INT;
BEGIN
    SELECT o.features INTO v_features
    FROM public.occasions o
    WHERE o.id = p_occasion;

    IF v_features IS NULL THEN
        v_features := '[]'::jsonb;
    END IF;

    v_norm_query := public.f_unaccent(coalesce(p_query, ''));

    IF v_norm_query IS NULL OR length(trim(v_norm_query)) = 0 THEN
        RETURN;
    END IF;

    v_effective_limit := LEAST(GREATEST(coalesce(p_limit, 50), 1), 200);

    RETURN QUERY
    SELECT 'event'::TEXT AS entity_type, e.id::BIGINT AS entity_id, e.title,
           LEFT(coalesce(e.description, ''), 120) AS snippet,
           GREATEST(extensions.similarity(e.search_doc, v_norm_query), 0.0)::REAL AS rank,
           e.start_time, e.place AS parent_id,
           jsonb_strip_nulls(jsonb_build_object(
             'end_time', e.end_time,
             'max_participants', e.max_participants,
             'place_title', p.title
           )) AS extra
    FROM public.events e
    LEFT JOIN public.places p ON p.id = e.place
    WHERE e.occasion = p_occasion
      AND e.is_hidden = FALSE
      AND (e.data->>'is_counseling_slot')::boolean IS NOT TRUE
      AND e.search_doc ILIKE '%' || v_norm_query || '%'

    UNION ALL

    SELECT 'place'::TEXT, p.id::BIGINT, p.title,
           LEFT(coalesce(p.description, ''), 120),
           GREATEST(extensions.similarity(p.search_doc, v_norm_query), 0.0)::REAL,
           NULL::TIMESTAMPTZ, NULL::BIGINT, NULL::JSONB
    FROM public.places p
    WHERE p.occasion = p_occasion
      AND p.is_hidden = FALSE
      AND p.search_doc ILIKE '%' || v_norm_query || '%'

    UNION ALL

    SELECT
      CASE
        WHEN i.type = 'song' THEN 'song'
        WHEN i.type = 'game' THEN 'game'
        ELSE 'info'
      END::TEXT,
      i.id::BIGINT, i.title,
      LEFT(coalesce(i.description, ''), 120),
      GREATEST(extensions.similarity(i.search_doc, v_norm_query), 0.0)::REAL,
      NULL::TIMESTAMPTZ, NULL::BIGINT, NULL::JSONB
    FROM public.information i
    WHERE i.occasion = p_occasion
      AND i.is_hidden = FALSE
      AND i.search_doc ILIKE '%' || v_norm_query || '%'
      AND (
        (i.type = 'song' AND EXISTS (
          SELECT 1 FROM jsonb_array_elements(v_features) f
          WHERE f->>'code' = 'songbook' AND (f->>'is_enabled')::boolean = TRUE
        ))
        OR
        (i.type = 'game' AND EXISTS (
          SELECT 1 FROM jsonb_array_elements(v_features) f
          WHERE f->>'code' = 'game' AND (f->>'is_enabled')::boolean = TRUE
        ))
        OR
        (i.type IS NULL OR i.type NOT IN ('song', 'game'))
      )

    UNION ALL

    SELECT 'news'::TEXT, n.id::BIGINT, NULL::TEXT,
           LEFT(coalesce(n.message, ''), 120),
           GREATEST(extensions.similarity(n.search_doc, v_norm_query), 0.0)::REAL,
           n.created_at, NULL::BIGINT, NULL::JSONB
    FROM public.news n
    WHERE n.occasion = p_occasion
      AND n.search_doc ILIKE '%' || v_norm_query || '%'

    ORDER BY rank DESC
    LIMIT v_effective_limit;
END;
$function$;
